### ISSUE TITLE
getAccessToken 一直等待

### ISSUE THREAD

**Issue by xjr100419** [Wechat-Group/WxJava#1845]
```
<dependency>
				<groupId>com.github.binarywang</groupId>
				<artifactId>weixin-java-mp</artifactId>
				<version>3.6.3.B</version>
			</dependency>
```
jstack 日志
```
"http-nio-8022-exec-1" #49 daemon prio=5 os_prio=0 tid=0x00007effd6330800 nid=0x5ead waiting on condition [0x00007eff513c5000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000f1c399e8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at org.apache.commons.pool2.impl.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:590)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:441)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:362)
	at redis.clients.util.Pool.getResource(Pool.java:49)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226)
	at me.chanjar.weixin.mp.config.impl.WxMpRedisConfigImpl.isAccessTokenExpired(WxMpRedisConfigImpl.java:54)
	at me.chanjar.weixin.mp.api.impl.WxMpServiceHttpClientImpl.getAccessToken(WxMpServiceHttpClientImpl.java:75)
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:337)
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:302)
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.post(BaseWxMpServiceImpl.java:281)
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.post(BaseWxMpServiceImpl.java:286)
	at me.chanjar.weixin.mp.api.impl.WxMpKefuServiceImpl.sendKefuMessage(WxMpKefuServiceImpl.java:32)
```

程序一直等待 假死

**Comment by binarywang** [comment]
不是被锁了吗？建议仔细检查下
