### ISSUE TITLE
最新版运行提示需要JedisPoolConfig，上个版本都正常

### ISSUE THREAD

**Issue by zxuanhong** [Wechat-Group/WxJava#1872]
### 简要描述
启动报错，，提示redis.clients.jedis.JedisPoolConfig没有找到，但是上个版本都是正常的啊，更新到最新的就报错了

### 模块版本情况
* WxJava 模块名: wx-java-miniapp-spring-boot-starter
* WxJava 版本号: 3.9.8.B

### 详细描述
1. 我设置配置加载是这个
```
wx:
  miniapp:
    appid: ${weixin.appid} #微信小程序的appid
    secret: ${weixin.secret} #微信小程序的Secret
    token: ${weixin.token} #微信小程序消息服务器配置的token
    aesKey: ${weixin.aesKey} #微信小程序消息服务器配置的EncodingAESKey
    msgDataFormat: JSON
    config-storage:
      type: memory
  pay:
    appId: ${weixin.appid} #微信公众号或者小程序等的appid
    mchId: ${weixin.mchId} #微信支付商户号
    mchKey: ${weixin.mchKey} #微信支付商户密钥
    keyPath: ${weixin.keyPath} # p12证书的位置，可以指定绝对路径，也可以指定类路径（以classpath:开头）
```
2. 本地运行就失败，上个版本3.6.0一切正常，，切换到3.9.8.B就出问题了一直提示需要JedisPoolConfig，这个一定要redis吗？？？

### 日志
```
java.lang.IllegalStateException: Failed to introspect Class [com.binarywang.spring.starter.wxjava.miniapp.config.WxMaAutoConfiguration] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@4b85612c]
        at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:481) ~[spring-core-5.2.10.RELEASE.jar:5.2.10.RELEASE]
        at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:358) ~[spring-core-5.2.10.RELEASE.jar:5.2.10.RELEASE]
        at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:414) ~[spring-core-5.2.10.RELEASE.jar:5.2.10.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.lambda$getTypeForFactoryMethod$2(AbstractAutowireCapableBeanFactory.java:742) ~[spring-beans-5.2.10.RELEASE.jar:5.2.10.RELEASE]
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:741) ~[spring-beans-5.2.10.RELEASE.jar:5.2.10.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:680) ~[spring-beans-5.2.10.RELEASE.jar:5.2.10.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:648) ~[spring-beans-5.2.10.RELEASE.jar:5.2.10.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1614) ~[spring-beans-5.2.10.RELEASE.jar:5.2.10.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:523) ~[spring-beans-5.2.10.RELEASE.jar:5.2.10.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:495) ~[spring-beans-5.2.10.RELEASE.jar:5.2.10.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:620) ~[spring-beans-5.2.10.RELEASE.jar:5.2.10.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:612) ~[spring-beans-5.2.10.RELEASE.jar:5.2.10.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.getBeansOfType(AbstractApplicationContext.java:1243) ~[spring-context-5.2.10.RELEASE.jar:5.2.10.RELEASE]
        at org.springframework.boot.SpringApplication.getExitCodeFromMappedException(SpringApplication.java:880) ~[spring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
        at org.springframework.boot.SpringApplication.getExitCodeFromException(SpringApplication.java:868) ~[spring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
        at org.springframework.boot.SpringApplication.handleExitCode(SpringApplication.java:855) ~[spring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
        at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:806) ~[spring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:325) ~[spring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
        at indi.zxiaozhou.Application.main(Application.java:33) ~[classes!/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[knowledge-manage-boot-1.0.0.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107) ~[knowledge-manage-boot-1.0.0.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[knowledge-manage-boot-1.0.0.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[knowledge-manage-boot-1.0.0.jar:na]
Caused by: java.lang.NoClassDefFoundError: redis/clients/jedis/JedisPoolConfig
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[na:na]
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166) ~[na:na]
        at java.base/java.lang.Class.getDeclaredMethods(Class.java:2309) ~[na:na]
        at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:463) ~[spring-core-5.2.10.RELEASE.jar:5.2.10.RELEASE]
        ... 29 common frames omitted
Caused by: java.lang.ClassNotFoundException: redis.clients.jedis.JedisPoolConfig
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[na:na]
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
```

**Comment by binarywang** [comment]
请先手动增加jedis依赖

**Comment by xiaohunsdt** [comment]
我在Oracle JDK 11里面就不需要添加！ 在openjdk11里面就需要添加！很奇怪！。。。

**Comment by totoro52** [comment]
我也遇到这个问题了，我排查了后发现是WxMaAutoConfiguration下的wxMaJedisConfigStorage方法导致的，但我设置的也是内存储存，但还是报了这个错误，暂时还没找到好的解决方案，只能引入jedis包

**Comment by tangmingze7280** [comment]
引入也报错呢   = =

**Comment by totoro52** [comment]
> 帖子也报错呢= =

报错什么内容呢
