### ISSUE TITLE
spring-boot 启动报错

### ISSUE THREAD

**Issue by jjLiek** [Wechat-Group/WxJava#1917]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~
# 另外如果确认属于bug，而且已明确如何修复，请参考贡献指南直接提交PR，省的浪费时间在这里描述问题，非常感谢配合

### 简要描述
__简单概括描述下你所遇到的问题。__

spring-boot 启动报错
### 模块版本情况
* WxJava 模块名: wx-java-miniapp-spring-boot-starter
* WxJava 版本号:4.0.0

### 详细描述
__尽量详细描述。请不要使用截图，尽量使用文字描述，代码直接贴上来，日志则请附在后面所示区域。__

### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将其url地址贴在这里__
g.springframework.beans.factory.BeanCreationException: Error creating bean with name 'service' defined in class path resource [com/binarywang/spring/starter/wxjava/miniapp/config/WxMaAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [cn.binarywang.wx.miniapp.api.WxMaService]: Factory method 'service' threw exception; nested exception is java.lang.IllegalArgumentException: class sun.misc.Launcher$AppClassLoader declares multiple JSON fields named ucp

**Comment by binarywang** [comment]
请注意查看最后一句。
另外请参考对应demo

**Comment by jjLiek** [comment]
项目中没有使用gson

**Comment by jjLiek** [comment]
Caused by: java.lang.IllegalArgumentException: class sun.misc.Launcher$AppClassLoader declares multiple JSON fields named ucp
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:172) ~[gson-2.8.6.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102) ~[gson-2.8.6.jar:na]
	at com.google.gson.Gson.getAdapter(Gson.java:458) ~[gson-2.8.6.jar:na]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:56) ~[gson-2.8.6.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127) ~[gson-2.8.6.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245) ~[gson-2.8.6.jar:na]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[gson-2.8.6.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127) ~[gson-2.8.6.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245) ~[gson-2.8.6.jar:na]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[gson-2.8.6.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127) ~[gson-2.8.6.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245) ~[gson-2.8.6.jar:na]
	at com.google.gson.Gson.toJson(Gson.java:704) ~[gson-2.8.6.jar:na]
	at com.google.gson.Gson.toJson(Gson.java:683) ~[gson-2.8.6.jar:na]
	at com.google.gson.Gson.toJson(Gson.java:638) ~[gson-2.8.6.jar:na]
	at com.google.gson.Gson.toJson(Gson.java:618) ~[gson-2.8.6.jar:na]
