### ISSUE TITLE
项目在本地可以正常启动，但是服务器上无法启动，Could not load org.apache.http.pool.AbstractConnPool$4.

### ISSUE THREAD

**Issue by wavecao** [Wechat-Group/WxJava#1954]
### 简要描述
项目在本地可以正常启动，但是服务器上无法启动

### 日志
严重: The web application [] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@6491abb1]) and a value of type [org.apache.xerces.jaxp.DocumentBuilderImpl] (value [org.apache.xerces.jaxp.DocumentBuilderImpl@38d1e394]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
一月 04, 2021 10:23:39 上午 org.apache.catalina.startup.HostConfig deployWAR
信息: Deployment of web application archive ***/***/ROOT.war has finished in 40,726 ms
一月 04, 2021 10:23:39 上午 org.apache.coyote.AbstractProtocol start
信息: Starting ProtocolHandler ["http-bio-9003"]
一月 04, 2021 10:23:39 上午 org.apache.catalina.startup.Catalina start
信息: Server startup in 40828 ms
一月 04, 2021 10:24:34 上午 org.apache.catalina.loader.WebappClassLoader loadClass
信息: Illegal access: this web application instance has been stopped already.  Could not load org.apache.http.pool.AbstractConnPool$4.  The eventual following stack trace is caused by an error thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access, and has no functional impact.
java.lang.IllegalStateException
 at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1612)
 at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1571)
 at org.apache.http.pool.AbstractConnPool.closeExpired(AbstractConnPool.java:648)
 at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.closeExpiredConnections(PoolingHttpClientConnectionManager.java:430)
 at me.chanjar.weixin.common.util.http.apache.DefaultApacheHttpClientBuilder$IdleConnectionMonitorThread.run(DefaultApacheHttpClientBuilder.java:313)

Exception in thread "IdleConnectionMonitorThread" java.lang.NoClassDefFoundError: org/apache/http/pool/AbstractConnPool$4
 at org.apache.http.pool.AbstractConnPool.closeExpired(AbstractConnPool.java:648)
 at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.closeExpiredConnections(PoolingHttpClientConnectionManager.java:430)
 at me.chanjar.weixin.common.util.http.apache.DefaultApacheHttpClientBuilder$IdleConnectionMonitorThread.run(DefaultApacheHttpClientBuilder.java:313)
Caused by: java.lang.ClassNotFoundException: org.apache.http.pool.AbstractConnPool$4
 at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1720)
 at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1571)
 ... 3 more

**Comment by binarywang** [comment]
注意分析关键信息：` java.lang.NoClassDefFoundError: org/apache/http/pool/AbstractConnPool$4`

**Comment by wavecao** [comment]
> 注意分析关键信息：` java.lang.NoClassDefFoundError: org/apache/http/pool/AbstractConnPool$4`
检查了一下，AbstractConnPool来自于httpcore这个jar包，而我的依赖文件夹中是存在这个包的

**Comment by binarywang** [comment]
再仔细分析下环境有何差异

**Comment by taneg** [comment]
直接查看最终运行的包里面是否包含此类，不以本地依赖为标准

**Comment by binarywang** [comment]
楼上说的很到位
