### ISSUE TITLE
wx-cp版本升级. springboot版本1.5.13.RELEASE  ..  redis集成出现问题

### ISSUE THREAD

**Issue by jinxiaoyi** [Wechat-Group/WxJava#2002]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~
# 另外如果确认属于bug，而且已明确如何修复，请参考贡献指南直接提交PR，省的浪费时间在这里描述问题，非常感谢配合

### 简要描述
你好,今天我把V3.9.0的版本升级到V4.0.0.使用StringRedisTemplate 在redis上存储access_token.

### 模块版本情况
* WxJava 模块名: 
* WxJava 版本号:V4.0.0

### 详细描述
运行过程中遇到如下错误.  也发现以前的帖子也出现过类似问题. 但是版本是V3.9.0.  楼主意思是升级版本就可以 .
但是我现在是V4.0.0还是遇到这个问题. 
spring-data-redis 版本是V1.8.12RELEASE. 请问这个该如何解决呢
顺便说一下.我的springboot是V1.X
### 日志
Caused by: java.lang.NoSuchMethodError: org.springframework.data.redis.connection.RedisConnection.set([B[BLorg/springframework/data/redis/core/types/Expiration;Lorg/springframework/data/redis/connection/RedisStringCommands$SetOption;)Ljava/lang/Boolean;
	at me.chanjar.weixin.common.util.locks.RedisTemplateSimpleDistributedLock.lambda$tryLock$0(RedisTemplateSimpleDistributedLock.java:78)
	at org.springframework.data.redis.core.RedisTemplate$2.doInRedis(RedisTemplate.java:282)
	at org.springframework.data.redis.core.RedisTemplate$2.doInRedis(RedisTemplate.java:277)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:207)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:169)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:157)
	at org.springframework.data.redis.core.RedisTemplate.executePipelined(RedisTemplate.java:277)
	at org.springframework.data.redis.core.RedisTemplate.executePipelined(RedisTemplate.java:273)
	at me.chanjar.weixin.common.util.locks.RedisTemplateSimpleDistributedLock.tryLock(RedisTemplateSimpleDistributedLock.java:77)
	at me.chanjar.weixin.common.util.locks.RedisTemplateSimpleDistributedLock.lock(RedisTemplateSimpleDistributedLock.java:52)
	at me.chanjar.weixin.cp.api.impl.WxCpServiceImpl.getAccessToken(WxCpServiceImpl.java:44)
	at me.chanjar.weixin.cp.api.impl.BaseWxCpServiceImpl.getAccessToken(BaseWxCpServiceImpl.java:99)
	at com.blackhole.app.sys.controller.data.CorpAppMsgReceiveLogController.getToken(CorpAppMsgReceiveLogController.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	... 91 common frames omitted

**Comment by binarywang** [comment]
这种问题就是jar包冲突导致，你要检查你自己项目的jar包版本问题

**Comment by gwenqing** [comment]
遇到了同样的问题，请问有解决方案吗

**Comment by jinxiaoyi** [comment]
> 遇到了同样的问题，请问有解决方案吗

当初是用了redission处理的. 没有用resttemplete.. 后来我们系统升级springboot2.x了. 现在还是用的RedisTemplate
