### ISSUE TITLE
本项目提现频率大概10秒一次,,,十天左右出现一次cpu 100%情况.

### ISSUE THREAD

**Issue by hiteny** [Wechat-Group/WxJava#2003]
### 简要描述
本项目提现频率大概10秒一次,,,十天左右出现一次cpu 100%情况.
一共出现了3次了

### 模块版本情况
* WxJava 模块名: com.github.binarywang:wx-java-pay-spring-boot-starter:
* WxJava 版本号:4.0.4.B

### 详细描述
报错地点:
"clusteredScheduler_Worker-1" #19 prio=5 os_prio=0 tid=0x00007efd16c42000 nid=0x30e1 runnable [0x00007efcf9fd9000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.thoughtworks.xstream.XStream.registerConverterDynamically(XStream.java:1131)
	at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:1075)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:593)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:515)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:484)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:430)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:411)
	at me.chanjar.weixin.common.util.xml.XStreamInitializer.getInstance(XStreamInitializer.java:44)
	at com.github.binarywang.wxpay.bean.result.BaseWxPayResult.fromXML(BaseWxPayResult.java:148)
	at com.github.binarywang.wxpay.service.impl.EntPayServiceImpl.entPay(EntPayServiceImpl.java:51)
	at org.teny.lm.service.CashMoneyService.entPay(CashMoneyService.java:63)

### 日志
[a.txt](https://github.com/Wechat-Group/WxJava/files/6002565/a.txt)

**Comment by tangdu** [comment]
找到一个帖子，看是否对你有帮忙；
解决方案是将对象做了缓存；https://blog.csdn.net/weixin_43767602/article/details/114824028

**Comment by hiteny** [comment]
> 找到一个帖子，看是否对你有帮忙；
> 解决方案是将对象做了缓存；https://blog.csdn.net/weixin_43767602/article/details/114824028

多谢,我也看到了这个帖子,但我看wxJava框架是在内部使用的Xtream,我无法修改

**Comment by binarywang** [comment]
> > 找到一个帖子，看是否对你有帮忙；
> > 解决方案是将对象做了缓存；https://blog.csdn.net/weixin_43767602/article/details/114824028
> 
> 多谢,我也看到了这个帖子,但我看wxJava框架是在内部使用的Xtream,我无法修改

明显你可以修改的，直接贡献代码就可以，欢迎自行修改并调试，确定没问题后PR即可

**Comment by cqyisbug** [comment]
[XstreamInitializer](https://github.com/cqyisbug/WxJava/blob/salus-dev/weixin-java-common/src/main/java/me/chanjar/weixin/common/util/xml/XStreamInitializer.java)
