### ISSUE TITLE
4.0.5.B版本WxCpMessage.toJson报null指针

### ISSUE THREAD

**Issue by adogcode** [Wechat-Group/WxJava#2010]
### 简要描述
4.0.5.B版本WxCpMessage.toJson报null指针，同样的代码在4.0.0版本没有问题，是改了哪些配置吗？自带的测试案例也没有通过

### 模块版本情况
* WxJava 模块名: weixin-java-cp
* WxJava 版本号:4.0.5.B

### 详细描述

java.lang.NullPointerException
	at me.chanjar.weixin.cp.bean.message.WxCpMessage.toJson(WxCpMessage.java:191)
	at me.chanjar.weixin.cp.bean.message.WxCpMessageTest.testTextBuild(WxCpMessageTest.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.testng.TestRunner.privateRun(TestRunner.java:766)
	at org.testng.TestRunner.run(TestRunner.java:587)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
### 日志
![image](https://user-images.githubusercontent.com/9071923/108984897-659a9400-76cb-11eb-8f21-1b0f2e839f97.png)

**Comment by binarywang** [comment]
新版本会修复
