### ISSUE TITLE
后台获取公众号传的media_id下载图片时报99999 无法获取到文件名

### ISSUE THREAD

**Issue by jansse-zhao** [Wechat-Group/WxJava#2060]
### 简要描述
前端通过chooseImage和uploadImage获得图片media_id后，回传后台，后台通过`wxService.getMaterialService().mediaDownload("mediaId");`下载图片时报错。`me.chanjar.weixin.common.error.WxErrorException: 错误代码：99999, 错误信息：无法获取到文件名`
----
### 模块版本情况
* WxJava 模块名: weixin-java-mp:3.6.0
* WxJava 版本号:3.6.0

### 日志
``` 
Caused by: me.chanjar.weixin.common.error.WxErrorException: 错误代码：99999, 错误信息：无法获取到文件名
	at me.chanjar.weixin.common.util.http.HttpResponseProxy.getFileName(HttpResponseProxy.java:61)
	at me.chanjar.weixin.common.util.http.HttpResponseProxy.getFileName(HttpResponseProxy.java:43)
	at me.chanjar.weixin.common.util.http.apache.ApacheMediaDownloadRequestExecutor.execute(ApacheMediaDownloadRequestExecutor.java:61)
	at me.chanjar.weixin.common.util.http.apache.ApacheMediaDownloadRequestExecutor.execute(ApacheMediaDownloadRequestExecutor.java:30)
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:341)
	... 94 more
```

**Comment by jansse-zhao** [comment]
### 是微信公众号测试平台测试的问题吗？

**Comment by jansse-zhao** [comment]
[微信开发者工具的问题，必须在真机上测试，冤枉WxJava](https://developers.weixin.qq.com/community/develop/doc/00084cba1905e0b0c0399ca5c56000?jumpto=comment&commentid=0004229335ca0841cd39f27185d0)

**Comment by binarywang** [comment]
好像以前也有人遇到此问题
