### ISSUE TITLE
小程序直播获取直播间助手报错

### ISSUE THREAD

**Issue by kk13562008** [Wechat-Group/WxJava#2070]
WxJava 模块名: weixin-java-miniapp
 WxJava 版本号: 4.0.0
详细描述 :
  weixin-java-miniapp -> WxMaLiveServiceImpl  -> getAssistantList( ) 使用了POST方法请求，微信要求的是使用GET

错误代码：
43001, 错误信息：require GET method rid: 606d52e0-101a945b-1de9c138，微信原始报文：{"errcode":43001,"errmsg":"require GET method rid: 606d52e0-101a945b-1de9c138"}
me.chanjar.weixin.common.error.WxErrorException: 错误代码：43001, 错误信息：require GET method rid: 606d52e0-101a945b-1de9c138，微信原始报文：{"errcode":43001,"errmsg":"require GET method rid: 606d52e0-101a945b-1de9c138"}
	at cn.binarywang.wx.miniapp.api.impl.BaseWxMaServiceImpl.executeInternal(BaseWxMaServiceImpl.java:275)
	at cn.binarywang.wx.miniapp.api.impl.BaseWxMaServiceImpl.execute(BaseWxMaServiceImpl.java:207)
	at cn.binarywang.wx.miniapp.api.impl.BaseWxMaServiceImpl.post(BaseWxMaServiceImpl.java:183)
	at cn.binarywang.wx.miniapp.api.impl.WxMaLiveServiceImpl.getAssistantList(WxMaLiveServiceImpl.java:215)

**Comment by binarywang** [comment]
请检查最新测试版本，版本号在首页

**Comment by binarywang** [comment]
楼主，到底参数该怎么传递，你测试过没？看官方文档，get请求居然body里传json？

**Comment by binarywang** [comment]
https://developers.weixin.qq.com/miniprogram/dev/framework/liveplayer/studio-api.html#12 官方文档地址
