### ISSUE TITLE
互联企业的消息推送接口返回字段类型和官网api不一致

### ISSUE THREAD

**Issue by pingtiandasheng** [Wechat-Group/WxJava#2148]
### 简要描述
接口返回字段类型和企业微信官网api不一致

### 模块版本情况
* WxJava 模块名:  weixin-java-cp   消息推送
* me.chanjar.weixin.cp.bean.message.WxCpMessageSendResult
* WxJava 版本号:4.1.0

### 详细描述
@SerializedName("invaliduser")
    private String invalidUser;
    @SerializedName("invalidparty")
    private String invalidParty;
    @SerializedName("invalidtag")
    private String invalidTag;

字段类型不一致，json转换会报错

### 日志
2021-06-08 14:55:33.452 [http-nio-8080-exec-2] INFO  c.m.a.config.exception.handler.MyExceptionHandler - java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 43 path $.invaliduser
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 43 path $.invaliduser
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at me.chanjar.weixin.cp.bean.message.WxCpMessageSendResult.fromJson(WxCpMessageSendResult.java:30)
	at me.chanjar.weixin.cp.api.impl.WxCpMessageServiceImpl.sendLinkedCorpMessage(WxCpMessageServiceImpl.java:49)
	at com.mychery.awesomeproject.service.impl.WxCommonServiceImpl.sendLinkedCorpMessage(WxCommonServiceImpl.java:51)
	at com.mychery.awesomeproject.service.impl.PushMessageServiceImpl.pushMessage(PushMessageServiceImpl.java:88)
	at com.mychery.awesomeproject.service.impl.PushMessageServiceImpl.PCPushMessage(PushMessageServiceImpl.java:55)
	at com.mychery.awesomeproject.controller.PushMessageController.messagePush(PushMessageController.java:44)
	at com.mychery.awesomeproject.controller.PushMessageController$$FastClassBySpringCGLIB$$98daf70f.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)

**Comment by binarywang** [comment]
请发出原始报文，看样子是由于出现了数组

**Comment by binarywang** [comment]
如果我没看错，官方文档是这样写的：

```
 {
   "errcode" : 0,
   "errmsg" : "ok",
   "invaliduser" : "userid1|userid2",
   "invalidparty" : "partyid1|partyid2",
   "invalidtag": "tagid1|tagid2"
 }

```

**Comment by pingtiandasheng** [comment]
> 请发出原始报文，看样子是由于出现了数组

是的，官网的返回实例现在是这样的
 {
   "errcode" : 0,
   "errmsg" : "ok",
   "invaliduser" : ["userid1","userid2","CorpId1/userid1","CorpId2/userid2"], // 不区分大小写，返回的列表都统一转为小写
   "invalidparty" : ["partyid1","partyid2","LinkedId1/partyid1","LinkedId2/partyid2"],
   "invalidtag":["tagid1","tagid2"]
 }

**Comment by pingtiandasheng** [comment]
> 如果我没看错，官方文档是这样写的：
> 
> ```
>  {
>    "errcode" : 0,
>    "errmsg" : "ok",
>    "invaliduser" : "userid1|userid2",
>    "invalidparty" : "partyid1|partyid2",
>    "invalidtag": "tagid1|tagid2"
>  }
> ```

我看到的官网咋是这样的
{
   "errcode" : 0,
   "errmsg" : "ok",
   "invaliduser" : ["userid1","userid2","CorpId1/userid1","CorpId2/userid2"], // 不区分大小写，返回的列表都统一转为小写
   "invalidparty" : ["partyid1","partyid2","LinkedId1/partyid1","LinkedId2/partyid2"],
   "invalidtag":["tagid1","tagid2"]
 }
api地址
https://work.weixin.qq.com/api/doc/90000/90135/90250

**Comment by binarywang** [comment]
你用的是互联企业的消息推送？看来两种消息返回结构不一致导致的

**Comment by pingtiandasheng** [comment]
> 你用的是互联企业的消息推送？看来两种消息返回结构不一致导致的

嗯嗯是的

**Comment by pingtiandasheng** [comment]
期待大神们丰富一下这一块

**Comment by binarywang** [comment]
期待不如自己马上行动，提交PR，这是目前最快的方法，你如果要等大佬行动，那可要且等了
