### ISSUE TITLE
V3对账单下载签名问题

### ISSUE THREAD

**Issue by vacuityv** [Wechat-Group/WxJava#2193]
### 简要描述
在获取到对账单地址，然后签名后访问，返回状态码200，但是由于头部不含签名报错了：
11:15:24.487 [main] WARN com.wechat.pay.contrib.apache.httpclient.auth.WechatPay2Validator - parameter error: empty Wechatpay-Serial, request-id=[v13vf9]
Caused by: org.apache.http.HttpException: 应答的微信支付签名验证失败

### 模块版本情况
* WxJava 模块名: 
* WxJava 版本号:V3

### 详细描述
通过对账单申请获取到账单地址，然后访问账单地址进行数据流下载，返回报文没有签名信息导致验签失败，和这个：https://developers.weixin.qq.com/community/pay/doc/000ee0c838083067d04bbad9b5b800 描述的一致

获取到：{"download_url":"https://api.mch.weixin.qq.com/v3/billdownload/file?token=dwVD7aBaKRMBXoqt-iTzmyvGoGrLGJwr6p3zC9dznJijRyBTrzc4y0tgaoycGBl8&tartype=gzip","hash_value":"23c2df2c63eb435552756e4cf100c546927a0d32","hash_type":"SHA1"}

然后签名后访问 https://api.mch.weixin.qq.com/v3/billdownload/file?token=dwVD7aBaKRMBXoqt-iTzmyvGoGrLGJwr6p3zC9dznJijRyBTrzc4y0tgaoycGBl8&tartype=gzip，获取到信息无签名导致微信sdk直接验签失败

### 日志
11:35:50.642 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection [id: 3][route: {s}->https://api.mch.weixin.qq.com:443] can be kept alive for 8.0 seconds
11:35:50.642 [main] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-3: set socket timeout to 0
11:35:50.642 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection released: [id: 3][route: {s}->https://api.mch.weixin.qq.com:443][total available: 1; route allocated: 1 of 2; total allocated: 1 of 20]
11:35:50.645 [main] WARN com.wechat.pay.contrib.apache.httpclient.auth.WechatPay2Validator - parameter error: empty Wechatpay-Serial, request-id=[c3rqwq]

org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.yhtech.onepay.gateway.util.wechat.WechatPayV3HttpClient.executeGet(WechatPayV3HttpClient.java:188)
	at com.yhtech.onepay.gateway.util.wechat.WechatPayV3HttpClient.getResponse(WechatPayV3HttpClient.java:119)
	at com.yhtech.onepay.gateway.util.wechat.WechatPayV3HttpClient.exexuteToGetStream(WechatPayV3HttpClient.java:72)
	at com.yhtech.onepay.gateway.WechatBillTest.t2(WechatBillTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:221)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.apache.http.HttpException: 应答的微信支付签名验证失败
	at com.wechat.pay.contrib.apache.httpclient.SignatureExec.executeWithSignature(SignatureExec.java:73)
	at com.wechat.pay.contrib.apache.httpclient.SignatureExec.execute(SignatureExec.java:49)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	... 28 more

**Comment by binarywang** [comment]
楼主走错地方了？
`com.yhtech.onepay.gateway.util.wechat.WechatPayV3HttpClient` 这是哪里的代码？

**Comment by vacuityv** [comment]
> 楼主走错地方了？
> `com.yhtech.onepay.gateway.util.wechat.WechatPayV3HttpClient` 这是哪里的代码？

这段是我们自己的代码，但是在里面调用了微信提供的sdk。微信所有的sdk都自动校验了签名，但是下载对账单是没有返回签名的，其他人也有遇到这个问题：https://developers.weixin.qq.com/community/pay/doc/000ee0c838083067d04bbad9b5b800

**Comment by binarywang** [comment]
微信的sdk跟我们的其实是有区别的，你为什么不尝试用我们的之后看有没有问题再来提问呢

**Comment by vacuityv** [comment]
> 微信的 sdk 跟我们的其实是有区别的，你为什么不尝试用我们的之后看有没有问题再来提问呢

抱歉，我以为这个是微信官方的，是我的问题
