### ISSUE TITLE
获取JsapiTicket时发生redis死锁

### ISSUE THREAD

**Issue by shijiuyan** [Wechat-Group/WxJava#2195]
### 简要描述
_获取JsapiTicket时发生redis死锁

### 模块版本情况
* WxJava 模块名: weixin-java-open
* WxJava 版本号:4.0.0

### 详细描述
WxOpenMpService mpService = configuration.getWxOpenComponentService().getWxMpServiceByAppid(appId);
 return mpService.getJsapiTicket(true);

### 日志
me.chanjar.weixin.common.error.WxRuntimeException: acquire timeouted
        at me.chanjar.weixin.common.util.locks.JedisDistributedLock.lock(JedisDistributedLock.java:30)
        at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.getTicket(BaseWxMpServiceImpl.java:162)
        at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.getJsapiTicket(BaseWxMpServiceImpl.java:187)
        at com.gotye.service.impl.WxOpenServiceImpl.getJsapiTicket(WxOpenServiceImpl.java:200)

**Comment by binarywang** [comment]
JedisDistributedLock 不建议使用，请更换其他实现

**Comment by tangmin823** [comment]
> JedisDistributedLock 不建议使用，请更换其他实现

您好，这个 JedisDistributedLock 有缺陷吧，请问有其他实现的方法吗？

**Comment by dazer007** [comment]
[通过WxJava获取微信AccessToken出现acquire timeouted问题](https://www.hyhblog.cn/2022/09/13/wxjava_acquire_timeouted/)
