### ISSUE TITLE
配置了两个公众号时SDK报错

### ISSUE THREAD

**Issue by hrj5032188** [Wechat-Group/WxJava#2228]
### 简要描述
我的项目里配置了两个微信的公众号
在请求接口时代码跑到了me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl#getWxMpConfigStorage方法内【图1】
在第428行的代码中返回的key一直是default【图2】，
而我的Map中的key应该都是微信公众号的appId
请问这里是我哪里的配置不正确吗
![image](https://user-images.githubusercontent.com/28888068/127617834-dfc8d31a-29ec-4f85-8600-5823b73565f7.png)
![image](https://user-images.githubusercontent.com/28888068/127618103-e2985f63-ec0f-42f6-a042-03f6de037ea1.png)

### 模块版本情况
* WxJava 模块名: weixin-java-mp
* WxJava 版本号: 4.1.3.B

### 详细描述
__尽量详细描述。请不要使用截图，尽量使用文字描述，代码直接贴上来，日志则请附在后面所示区域。__
![image](https://user-images.githubusercontent.com/28888068/127618243-5232335f-d422-4763-9b78-8e0e029a0b63.png)

### 日志
java.lang.NullPointerException: null
	at me.chanjar.weixin.mp.api.impl.WxMpOAuth2ServiceImpl.buildAuthorizationUrl(WxMpOAuth2ServiceImpl.java:35)
	at com.ruoyi.project.wechat.controller.WxMpOAuthController.authorize(WxMpOAuthController.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)

**Comment by binarywang** [comment]
没看到你的配置到底怎么写的
