### ISSUE TITLE
关于微信支付4.1.0版本支付回调问题

### ISSUE THREAD

**Issue by kelv1n1n** [Wechat-Group/WxJava#2275]
### 简要描述
在H5页面发起微信支付，支付成功后回调接口接收微信返回的结果是1，然后使用wxPayService.parseOrderNotifyResultu去解析就会异常

### 模块版本情况
* WxJava 模块名: weixin-java-pay
* WxJava 版本号:4.1.0（旧版本不予支持，谢谢配合）

### 详细描述
h5页面发起支付成功后，微信支付回调通知接口，返回的报文正常应该是一堆xml，但是我这边接收到打印出来的是1
然后就抛了出了一下异常，不知道是接收的问题，还是微信返回本来就是错的
@ApiOperation(value = "支付回调通知处理")
	@PostMapping("/notify/order")
	public String parseOrderNotifyResult(@RequestBody String xmlData) throws WxPayException {
		System.out.println("进入支付回调通知......");
		System.out.println("回调原参数......" + xmlData);//报错位置 打印出来xmlData是：1
		final WxPayOrderNotifyResult notifyResult = this.wxService.parseOrderNotifyResult(xmlData);
		// TODO 根据自己业务场景需要构造返回对象

### 日志
进入支付回调通知......
回调原参数......1
2021-08-24 16:17:01.013 ERROR 9038 --- [ XNIO-1 task-29] o.s.c.l.e.ExceptionTranslator   : 服务器异常

com.github.binarywang.wxpay.exception.WxPayException: 发生异常！
	at com.github.binarywang.wxpay.service.impl.BaseWxPayServiceImpl.parseOrderNotifyResult(BaseWxPayServiceImpl.java:333)
	at com.github.binarywang.wxpay.service.impl.BaseWxPayServiceImpl.parseOrderNotifyResult(BaseWxPayServiceImpl.java:309)
	at com.cnsci.pay.controller.WxPayController.parseOrderNotifyResult(WxPayController.java:276)
	at com.cnsci.pay.controller.WxPayController$$FastClassBySpringCGLIB$$69abfa04.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at com.cnsci.pay.controller.WxPayController$$EnhancerBySpringCGLIB$$54834629.parseOrderNotifyResult(<generated>)
	at sun.reflect.GeneratedMethodAccessor247.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at 
Caused by: com.thoughtworks.xstream.io.StreamException: 
	at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:124)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readRealEvent(AbstractPullReader.java:148)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readEvent(AbstractPullReader.java:141)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.move(AbstractPullReader.java:118)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.moveDown(AbstractPullReader.java:103)
	at com.thoughtworks.xstream.io.xml.XppReader.<init>(XppReader.java:63)
	at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:54)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1338)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1329)
	at com.github.binarywang.wxpay.bean.notify.WxPayOrderNotifyResult.fromXML(WxPayOrderNotifyResult.java:338)
	at com.github.binarywang.wxpay.service.impl.BaseWxPayServiceImpl.parseOrderNotifyResult(BaseWxPayServiceImpl.java:316)
	... 81 common frames omitted
Caused by: org.xmlpull.v1.XmlPullParserException: only whitespace content allowed before start tag and not 1 (position: START_DOCUMENT seen 1... @1:1) 
	at org.xmlpull.mxp1.MXParser.parseProlog(MXParser.java:1519)
	at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1395)
	at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
	at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:109)
	... 91 common frames omitted

**Comment by kelv1n1n** [comment]
解决了

**Comment by chrelyonly** [comment]
您好,我4.2.0也出现这个文件,请问是如何解决的

**Comment by slhou** [comment]
> 解决了

怎么解决的
