### ISSUE TITLE
org.xml.sax.SAXNotRecognizedException: unrecognized feature http://apache.org/xml/features/disallow-doctype-decl 	at me.chanjar.weixin.common.util.XmlUtils.xml2Map

### ISSUE THREAD

**Issue by almpazel** [Wechat-Group/WxJava#2299]
Exception in thread "main" me.chanjar.weixin.common.error.WxRuntimeException: org.xml.sax.SAXNotRecognizedException: unrecognized feature http://apache.org/xml/features/disallow-doctype-decl
	at me.chanjar.weixin.common.util.XmlUtils.xml2Map(XmlUtils.java:45)
	at test.TestWechat.main(TestWechat.kt:31)
Caused by: org.xml.sax.SAXNotRecognizedException: unrecognized feature http://apache.org/xml/features/disallow-doctype-decl
	at org.gjt.xpp.sax2.Driver.setFeature(Driver.java:178)
	at org.dom4j.io.SAXReader.setFeature(SAXReader.java:283)
	at me.chanjar.weixin.common.util.XmlUtils.xml2Map(XmlUtils.java:33)
	... 1 more

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/WxJava/issues/1734  楼主先参考下这里的解决方案，能否解决
