### ISSUE TITLE
微信开放平台--微信授权登录app登录调用方法报空指针异常

### ISSUE THREAD

**Issue by tpslitao** [Wechat-Group/WxJava#2333]
### 简要描述
微信授权登录app登录调用方法报空指针异常

### 模块版本情况
* WxJava 模块名: weixin-java-open
* WxJava 版本号: 4.1.0

### 详细描述
微信授权登录app登录调用方法报空指针异常
接口类：WxOAuth2Service 
实例化实现类：WxOpenOAuth2ServiceImpl(appId,appSecret)
调用方法：wxOAuth2Service.getAccessToken(authCode)
### 日志
java.lang.NullPointerException: null
at me.chanjar.weixin.common.util.http.apache.ApacheSimpleGetRequestExecutor.execute(ApacheSimpleGetRequestExecutor.java:40) ~[weixin-java-common-4.0.0.jar:na]
at me.chanjar.weixin.common.util.http.apache.ApacheSimpleGetRequestExecutor.execute(ApacheSimpleGetRequestExecutor.java:21) ~[weixin-java-common-4.0.0.jar:na]
at me.chanjar.weixin.open.api.impl.WxOpenServiceAbstractImpl.execute(WxOpenServiceAbstractImpl.java:48) ~[weixin-java-open-4.0.0.jar:na]
at me.chanjar.weixin.open.api.impl.WxOpenServiceApacheHttpClientImpl.get(WxOpenServiceApacheHttpClientImpl.java:60) ~[weixin-java-open-4.0.0.jar:na]
at me.chanjar.weixin.open.api.impl.WxOpenOAuth2ServiceImpl.getOAuth2AccessToken(WxOpenOAuth2ServiceImpl.java:36) ~[weixin-java-open-4.0.0.jar:na]
at me.chanjar.weixin.open.api.impl.WxOpenOAuth2ServiceImpl.getAccessToken(WxOpenOAuth2ServiceImpl.java:46) ~[weixin-java-open-4.0.0.jar:na]

**Comment by Bamboo898** [comment]
我也遇到了这个问题，版本: 4.2.0

**Comment by Bamboo898** [comment]
临时解决方案: 如果仅仅只是需要通过WxOpenOAuth2ServiceImpl获取用户access token的朋友，可以在new出对象后，调用一下setWxOpenConfigStorage就可以了。
``` java
WxOpenOAuth2ServiceImpl service = new WxOpenOAuth2ServiceImpl(appId, secred);
service.setWxOpenConfigStorage(new WxOpenInMemoryConfigStorage());
```

**Comment by binarywang** [comment]
楼上说的对，单元测试里有代码演示
