### ISSUE TITLE
WxOpenComponentServiceImpl.java:81 会npe异常。

### ISSUE THREAD

**Issue by hzdavid** [Wechat-Group/WxJava#2413]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~
# 另外如果确认属于bug，而且已明确如何修复，请参考贡献指南直接提交PR，省的浪费时间在这里描述问题，非常感谢配合

### 简要描述
__简单概括描述下你所遇到的问题。__

### 模块版本情况
* WxJava 模块名: WxOpenComponentServiceImpl.java 
* WxJava 版本号:（旧版本不予支持，谢谢配合）. 4.2.0

### 详细描述
__尽量详细描述。请不要使用截图，尽量使用文字描述，代码直接贴上来，日志则请附在后面所示区域。__

Caused by: java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:?]
        at me.chanjar.weixin.open.api.impl.WxOpenComponentServiceImpl.getWxMaServiceByAppid() ~[weixin-java-open-4.2.0.jar!/:?]

### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将其url地址贴在这里__

**Comment by hzdavid** [comment]
> 

jdk 11

**Comment by binarywang** [comment]
自己看是哪个代码出现空指针，是不是少设置了什么东西

**Comment by hzdavid** [comment]
> 自己看是哪个代码出现空指针，是不是少设置了什么东西

![image](https://user-images.githubusercontent.com/4660219/143846744-71b1a36e-4612-444a-a856-7ac8048c553a.png)

**Comment by hzdavid** [comment]
> 自己看是哪个代码出现空指针，是不是少设置了什么东西

![image](https://user-images.githubusercontent.com/4660219/143846931-c49091ef-a9e6-4693-86b9-6927f70cfb92.png)

**Comment by hzdavid** [comment]
> Caused by: java.lang.NullPointerException
> at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:?]
> at me.chanjar.weixin.open.api.impl.WxOpenComponentServiceImpl.getWxMaServiceByAppid() ~[weixin-java-open-4.2.0.jar!/:?]

Caused by: java.lang.NullPointerException
at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:?]
at me.chanjar.weixin.open.api.impl.WxOpenComponentServiceImpl.getWxMaServiceByAppid() ~[weixin-java-open-4.2.0.jar!/:?]
