### ISSUE TITLE
调用WxMpService的临时素材下载方法无效,提示错误代码:99999,文件名不存在

### ISSUE THREAD

**Issue by condyRen** [Wechat-Group/WxJava#2465]
当调用接口获取的临时素材为视频时，会出现无法获取到文件名的错误。定位调试时发现是因为content-type不对导致的。
获取临时素材为视频是，微信返回的为视频地址[文档](https://developers.weixin.qq.com/doc/offiaccount/Asset_Management/Get_temporary_materials.html)，相关代码会通过response的header来获取content-disposition，但当为视频的时候，此值为空。因此抛出错误。代码如下：

```
public class HttpResponseProxy {
  
  private String getFileName(CloseableHttpResponse response) throws WxErrorException {
    Header[] contentDispositionHeader = response.getHeaders("Content-disposition");
    if (contentDispositionHeader == null || contentDispositionHeader.length == 0) {
      throw new WxErrorException("无法获取到文件名，Content-disposition为空");
    }

    return this.extractFileNameFromContentString(contentDispositionHeader[0].getValue());
  }
```

目前使用的3.3.0版本有错误，看了新版本的代码，应该存在相同的问题。错误栈信息如下：
```
Caused by: me.chanjar.weixin.common.error.WxErrorException: 错误: Code=99999, Msg=无法获取到文件名
	at me.chanjar.weixin.common.util.http.HttpResponseProxy.getFileName(HttpResponseProxy.java:61) ~[weixin-java-common-3.3.0.jar:na]
	at me.chanjar.weixin.common.util.http.HttpResponseProxy.getFileName(HttpResponseProxy.java:43) ~[weixin-java-common-3.3.0.jar:na]
	at me.chanjar.weixin.common.util.http.apache.ApacheMediaDownloadRequestExecutor.execute(ApacheMediaDownloadRequestExecutor.java:58) ~[weixin-java-common-3.3.0.jar:na]
	at me.chanjar.weixin.common.util.http.apache.ApacheMediaDownloadRequestExecutor.execute(ApacheMediaDownloadRequestExecutor.java:27) ~[weixin-java-common-3.3.0.jar:na]
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:323) ~[weixin-java-mp-3.3.0.jar:na]
	... 82 common frames omitted

```

**Comment by scruel** [comment]
请求头的 content-type？不对的话应该是什么？

**Comment by condyRen** [comment]
> 请求头的 content-type？不对的话应该是什么？

application/json 或者是 plain/text

**Comment by scruel** [comment]
> > 请求头的 content-type？不对的话应该是什么？
> 
> application/json 或者是 plain/text

看了下文档，这个请求也没有 body 吧，怎么会跟请求头的 content-type 有关系呢？

**Comment by condyRen** [comment]
> > > 请求头的 content-type？不对的话应该是什么？
> > 
> > 
> > application/json 或者是 plain/text
> 
> 看了下文档，这个请求也没有 body 吧，怎么会跟请求头的 content-type 有关系呢？

你是说请求body？这个跟请求body没关系。content-type是返回的时候携带的。嗯。其实是response head中的，不能叫请求头，是响应头。响应的时候视频和文本图片什么的是有区别的。

**Comment by scruel** [comment]
抱歉没看懂，请把完整过程复述处理，或者提供 demo 工程。

**Comment by condyRen** [comment]
当调用接口获取的临时素材为视频时，会出现无法获取到文件名的错误。
反馈的问题中微信的文档链接已经附上了，简单来说就是视频和别的返回的内容并不一样，视频返回的仅仅是一个视频的url地址
内容是json格式的，这时候不是文件，无法通过content-disposition获取文件名，而别的素材是直接返回素材内容本身可以通过content-disposition获取文件名。

可以调用一下这个接口试试，先上传一个视频素材，再调用获取功能。

目前demo真没有，已经修改直接调用微信接口来获取了，没有使用项目的API
