### ISSUE TITLE
获取带参数的二维码时 ,空指针异常

### ISSUE THREAD

**Issue by JoeNumberOne** [Wechat-Group/WxJava#2548]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~
# 另外如果确认属于bug，而且已明确如何修复，请参考贡献指南直接提交PR，省的浪费时间在这里描述问题，非常感谢配合

### 简要描述
__简单概括描述下你所遇到的问题。__
获取带参数的二维码时 ,空指针异常

### 模块版本情况
* WxJava 模块名: 
* WxJava 版本号:4.2.0

### 详细描述
__尽量详细描述。请不要使用截图，尽量使用文字描述，代码直接贴上来，日志则请附在后面所示区域。__
获取带参数的二维码的时候,报空指针,查看日志发现系统获取final WxMpConfigStorage config = this.getWxMpConfigStorage();时config为空,不知道该怎么解决,麻烦看一下

### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将其url地址贴在这里__
java.lang.NullPointerException: null
	at me.chanjar.weixin.mp.api.impl.WxMpServiceHttpClientImpl.getAccessToken(WxMpServiceHttpClientImpl.java:69) ~[weixin-java-mp-4.1.0.jar:na]
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:380) ~[weixin-java-mp-4.1.0.jar:na]
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:344) ~[weixin-java-mp-4.1.0.jar:na]
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.post(BaseWxMpServiceImpl.java:298) ~[weixin-java-mp-4.1.0.jar:na]
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.post(BaseWxMpServiceImpl.java:303) ~[weixin-java-mp-4.1.0.jar:na]
	at me.chanjar.weixin.mp.api.impl.WxMpQrcodeServiceImpl.getQrCodeTicket(WxMpQrcodeServiceImpl.java:79) ~[weixin-java-mp-4.1.0.jar:na]
	at me.chanjar.weixin.mp.api.impl.WxMpQrcodeServiceImpl.createQrCode(WxMpQrcodeServiceImpl.java:58) ~[weixin-java-mp-4.1.0.jar:na]

**Comment by JoeNumberOne** [comment]
版本改成4.2.0也是同样的问题
