### ISSUE TITLE
旧的spring-data-redis版本引入最新的weixin-java-miniapp无法使用

### ISSUE THREAD

**Issue by gwenqing** [Wechat-Group/WxJava#2575]
项目使用的是spring-data-redis 1.8.17.RELEASE，使用了最新版本的weixin-java-miniapp后出现异常
```
java.lang.NoSuchMethodError: org.springframework.data.redis.connection.RedisConnection.set([B[BLorg/springframework/data/redis/core/types/Expiration;Lorg/springframework/data/redis/connection/RedisStringCommands$SetOption;)Ljava/lang/Boolean;
        at me.chanjar.weixin.common.util.locks.RedisTemplateSimpleDistributedLock.lambda$tryLock$0(RedisTemplateSimpleDistributedLock.java:78)
	at org.springframework.data.redis.core.RedisTemplate$2.doInRedis(RedisTemplate.java:282)
	at org.springframework.data.redis.core.RedisTemplate$2.doInRedis(RedisTemplate.java:277)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:207)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:169)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:157)
	at org.springframework.data.redis.core.RedisTemplate.executePipelined(RedisTemplate.java:277)
	at org.springframework.data.redis.core.RedisTemplate.executePipelined(RedisTemplate.java:273)
	at me.chanjar.weixin.common.util.locks.RedisTemplateSimpleDistributedLock.tryLock(RedisTemplateSimpleDistributedLock.java:77)
	at me.chanjar.weixin.common.util.locks.RedisTemplateSimpleDistributedLock.tryLock(RedisTemplateSimpleDistributedLock.java:89)
	at cn.binarywang.wx.miniapp.api.impl.BaseWxMaServiceImpl.getAccessToken(BaseWxMaServiceImpl.java:163)
	at cn.binarywang.wx.miniapp.api.impl.BaseWxMaServiceImpl.getAccessToken(BaseWxMaServiceImpl.java:150)
```
出现错误的原因是mp使用的是2.X版本的data-redis，与项目中引用的部分不兼容。
在不升级spring boot的情况下，有没有解决办法？

**Comment by binarywang** [comment]
这个确实没有太好办法，无法同时兼顾两个版本
