### ISSUE TITLE
委托代扣[支付中签约]接口报错

### ISSUE THREAD

**Issue by guoping007** [Wechat-Group/WxJava#2706]
### 简要描述
委托代扣[支付中签约]接口（https://pay.weixin.qq.com/wiki/doc/api/wxpay_v2/papay/chapter3_5.shtml）报错

### 模块版本情况
* WxJava 模块名: weixin-java-pay
* WxJava 版本号:4.3.0

### 详细描述
委托代扣[支付中签约]接口报错
### 日志

```
2022-06-21 10:11:37.915 [http-nio-8080-exec-1-1655777494868] INFO  c.g.b.w.s.i.WxPayServiceImpl : 
【请求地址】：https://api.mch.weixin.qq.com/pay/contractorder
【请求数据】：<xml>
  <appid>wx286150fcfe66751c</appid>
  <mch_id>1603687014</mch_id>
  <nonce_str>1655777497246</nonce_str>
  <sign>B40280457BF8DB1BA3BDE96E75766480</sign>
  <contract_mchid>1603687014</contract_mchid>
  <contract_appid>wx286150fcfe66751c</contract_appid>
  <out_trade_no>PAY2022062100000045</out_trade_no>
  <device_info>WEB</device_info>
  <body>产品名称</body>
  <detail>产品描述</detail>
  <attach>test</attach>
  <notify_url>https://127.0.0.1/intf/wxpay/notify/order</notify_url>
  <total_fee>1000</total_fee>
  <spbill_create_ip>127.0.0.1</spbill_create_ip>
  <trade_type>MWEB</trade_type>
  <openid>ouX9p0xldxGZIVfsZnnRLGcBUsGU</openid>
  <plan_id>1234</plan_id>
  <contract_code>PAPAY2022062100000044</contract_code>
  <request_serial>2022062100000046</request_serial>
  <contract_display_account>测试</contract_display_account>
  <contract_notify_url>https://127.0.0.1/intf/wxpay/notify/order</contract_notify_url>
  <contract_outerid>测试</contract_outerid>
</xml>
【响应数据】：<xml><return_code><![CDATA[SUCCESS]]></return_code>
<return_msg><![CDATA[OK]]></return_msg>
<result_code><![CDATA[SUCCESS]]></result_code>
<contract_result_code><![CDATA[SUCCESS]]></contract_result_code>
<mch_id><![CDATA[1603687014]]></mch_id>
<appid><![CDATA[wx286150fcfe66751c]]></appid>
<prepay_id><![CDATA[wx21101136807417d9ec1a168fb517580000]]></prepay_id>
<trade_type><![CDATA[MWEB]]></trade_type>
<mweb_url><![CDATA[https://wx.tenpay.com/cgi-bin/mmpayweb-bin/checkmweb?prepay_id=wx21101136807417d9ec1a168fb517580000&package=3225915401]]></mweb_url>
<plan_id><![CDATA[142818]]></plan_id>
<request_serial><![CDATA[2022062100000046]]></request_serial>
<contract_code><![CDATA[PAPAY2022062100000044]]></contract_code>
<contract_display_account><![CDATA[测试]]></contract_display_account>
<out_trade_no><![CDATA[PAY2022062100000045]]></out_trade_no>
<nonce_str><![CDATA[Rraf8fbTpE1qgHTA]]></nonce_str>
<device_info><![CDATA[WEB]]></device_info>
<sign><![CDATA[0969ACF66502587EFD33398CDA8EDFCE]]></sign>
</xml>
2022-06-21 10:11:39.950 [http-nio-8080-exec-1-1655777494868] ERROR c.n.l.c.GlobalExceptionHandler : Exception,
com.thoughtworks.xstream.mapper.CannotResolveClassException: xml
	at com.thoughtworks.xstream.mapper.DefaultMapper.realClass(DefaultMapper.java:81)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:125)
	at com.thoughtworks.xstream.mapper.DynamicProxyMapper.realClass(DynamicProxyMapper.java:55)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:125)
	at com.thoughtworks.xstream.mapper.PackageAliasingMapper.realClass(PackageAliasingMapper.java:88)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:125)
	at com.thoughtworks.xstream.mapper.ClassAliasingMapper.realClass(ClassAliasingMapper.java:79)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:125)
	at com.thoughtworks.xstream.mapper.ArrayMapper.realClass(ArrayMapper.java:74)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:125)
	at com.thoughtworks.xstream.mapper.SecurityMapper.realClass(SecurityMapper.java:71)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:125)
	at com.thoughtworks.xstream.mapper.CachingMapper.realClass(CachingMapper.java:47)
	at com.thoughtworks.xstream.core.util.HierarchicalStreams.readClassType(HierarchicalStreams.java:29)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:135)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1421)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1399)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1284)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1275)
	at com.github.binarywang.wxpay.bean.result.BaseWxPayResult.fromXML(BaseWxPayResult.java:154)
	at com.github.binarywang.wxpay.service.impl.WxEntrustPapServiceImpl.paySign(WxEntrustPapServiceImpl.java:86)

```

**Comment by zhongjun96** [comment]
最新版本使用你的数据解析正常。建议尝试升级版本试试 
<img width="1596" alt="image" src="https://user-images.githubusercontent.com/18225577/174727204-37abe159-8ea1-4b08-bb68-3bc4d5cf34ac.png">

**Comment by zzhujing** [comment]
我项目也遇到相同情况,debug发现是签约那边的api响应实体上没有添加对应@XStreamAlias("xml"),导致xml解析失败

几种解决方式,
1. 是通过全局XmlConfig.fastMode=true来使用另外一套解析 (推荐)
2. 在对应实体上补充@XStreamAlias("xml") (需要改源码)
3. 自己解析xml(麻烦)

**Comment by binarywang** [comment]
> 

欢迎PR，改源码很简单，请直接操作吧

**Comment by binarywang** [comment]
> 我项目也遇到相同情况,debug发现是签约那边的api响应实体上没有添加对应@XStreamAlias("xml"),导致xml解析失败
> 
> 几种解决方式,
> 
> 1. 是通过全局XmlConfig.fastMode=true来使用另外一套解析 (推荐)
> 2. 在对应实体上补充@XStreamAlias("xml") (需要改源码)
> 3. 自己解析xml(麻烦)


欢迎PR，改源码很简单，请直接操作吧
