### ISSUE TITLE
加载出错

### ISSUE THREAD

**Issue by hanxiang-li** [Wechat-Group/WxJava#2860]
### 模块版本情况
* WxJava 模块名:  mp
* WxJava 版本号: 4.4.0

### 详细描述
我使用java-mp制作了一个jar插件，程序去动态的加载这个jar，加载实例化的时候出现了 找不类，

### 日志
```
java.io.IOException: Class not found
	at org.objectweb.asm.ClassReader.readStream(ClassReader.java:315)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:299)
	at org.noear.solon.aspect.asm.TargetClassVisitor.initMethodBeanByParent(TargetClassVisitor.java:90)
	at org.noear.solon.aspect.asm.TargetClassVisitor.visit(TargetClassVisitor.java:30)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:569)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
	at org.noear.solon.aspect.asm.AsmProxy.newProxyInstance(AsmProxy.java:88)
	at org.noear.solon.aspect.BeanInvocationHandler.<init>(BeanInvocationHandler.java:40)
	at org.noear.solon.aspect.BeanInvocationHandler.<init>(BeanInvocationHandler.java:26)
	at org.noear.solon.aspect.BeanProxy.getProxy(BeanProxy.java:33)
	at org.noear.solon.core.BeanWrap.proxySet(BeanWrap.java:112)
	at org.noear.solon.aspect.AspectUtil.binding(AspectUtil.java:32)
	at org.noear.solon.aspect.integration.XPluginImp.lambda$start$1(XPluginImp.java:23)
	at org.noear.solon.core.AopContext.lambda$tryCreateBean$10(AopContext.java:398)
	at org.noear.solon.core.AopContext.tryCreateBean0(AopContext.java:427)
	at org.noear.solon.core.AopContext.tryCreateBean(AopContext.java:395)
	at org.noear.solon.core.AopContext.lambda$beanScan$9(AopContext.java:354)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.noear.solon.core.AopContext.beanScan(AopContext.java:349)
	at org.noear.solon.core.AopContext.beanScan(AopContext.java:328)
	at cn.work.wechat.XWechatMpPluginImpl.start(XWechatMpPluginImpl.java:27)
	at org.noear.solon.core.PluginEntity.start(PluginEntity.java:85)
	at org.noear.solon.hotplug.PluginPackage.start(PluginPackage.java:102)
	at cn.work.Test.init(Test.java:28)
	at cn.work.WorkApp.main(WorkApp.java:40)
```
`
com.thoughtworks.xstream.mapper.CannotResolveClassException: me.chanjar.weixin.mp.bean.message.WxMpXmlMessage
`

**Comment by hanxiang-li** [comment]
我在 weixin-java-common 模块的 me.chanjar.weixin.common.util.xml => XStreamInitializer 中修改指定的类加载器 CannotResolveClassException 这个异常解决了，是否可以更改一下，如果指定了类加载器就用指定的，没有指定就用当前线程的

**Comment by hanxiang-li** [comment]
![image](https://user-images.githubusercontent.com/45918130/198815673-f97d58b6-ba2f-446c-bbf8-087ac98de7db.png)

这是修改后的代码

**Comment by binarywang** [comment]
欢迎直接PR代码

**Comment by hanxiang-li** [comment]
https://github.com/Wechat-Group/WxJava/pull/2861 已经提交了
