### ISSUE TITLE
调用微信统一下单接口错误：v3请求结构异常

### ISSUE THREAD

**Issue by coder8088** [Wechat-Group/WxJava#2877]
### 简要描述
简单概括描述下你所遇到的问题。
使用WxPayService.createOrderV3方法创建微信支付UnifiedOrder时，发生“v3请求构造异常”，具体日志见下方。

### 模块版本情况
WxJava 模块名: wx-java-pay-spring-boot-starter
WxJava 版本号: 4.4.0

### 详细描述
在本地测试支付的时候没有发生该异常，通过maven打包jar放到服务器上之后，调用接口发生该异常。检查证书路径没问题，先后使用classpath和绝对路径测试，依然发生该异常。更换最新生成的证书也依然存在该异常。
证书文件都是最新创建的，在jar包中也检查了文件内容是正确的。

```yaml
wx.pay.private-key-path=classpath:cert/apiclient_key.pem
wx.pay.private-cert-path=classpath:cert/apiclient_cert.pem
```

### 日志

```
com.github.binarywang.wxpay.exception.WxPayException: v3请求构造异常！
at com.github.binarywang.wxpay.config.WxPayConfig.initApiV3HttpClient(WxPayConfig.java:302) ~[weixin-java-pay-4.4.0.jar!/:na]
at com.github.binarywang.wxpay.service.impl.WxPayServiceApacheHttpImpl.createApiV3HttpClient(WxPayServiceApacheHttpImpl.java:303) ~[weixin-java-pay-4.4.0.jar!/:na]
at com.github.binarywang.wxpay.service.impl.WxPayServiceApacheHttpImpl.postV3(WxPayServiceApacheHttpImpl.java:93) ~[weixin-java-pay-4.4.0.jar!/:na]
at com.github.binarywang.wxpay.service.impl.BaseWxPayServiceImpl.unifiedOrderV3(BaseWxPayServiceImpl.java:683) ~[weixin-java-pay-4.4.0.jar!/:na]
at com.github.binarywang.wxpay.service.impl.BaseWxPayServiceImpl.createOrderV3(BaseWxPayServiceImpl.java:666) ~[weixin-java-pay-4.4.0.jar!/:na]
at com.hbchida.miniapp.web.service.WalletService.createRechargeOrder(WalletService.java:56) ~[classes!/:1.0]
at com.hbchida.miniapp.web.controller.WalletController.recharge(WalletController.java:48) ~[classes!/:1.0]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) [spring-web-5.3.23.jar!/:5.3.23]
at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) [spring-web-5.3.23.jar!/:5.3.23]
at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) [spring-webmvc-5.3.23.jar!/:5.3.23]
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) [spring-webmvc-5.3.23.jar!/:5.3.23]
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) [spring-webmvc-5.3.23.jar!/:5.3.23]
at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) [spring-webmvc-5.3.23.jar!/:5.3.23]
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1071) [spring-webmvc-5.3.23.jar!/:5.3.23]
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964) [spring-webmvc-5.3.23.jar!/:5.3.23]
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.3.23.jar!/:5.3.23]
at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) [spring-webmvc-5.3.23.jar!/:5.3.23]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:681) [tomcat-embed-core-9.0.65.jar!/:na]
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) [spring-webmvc-5.3.23.jar!/:5.3.23]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) [tomcat-embed-core-9.0.65.jar!/:na]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) [tomcat-embed-core-9.0.65.jar!/:na]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.65.jar!/:na]
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-embed-websocket-9.0.65.jar!/:na]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.65.jar!/:na]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.65.jar!/:na]
at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) [spring-web-5.3.23.jar!/:5.3.23]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.23.jar!/:5.3.23]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.65.jar!/:na]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.65.jar!/:na]
at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-5.3.23.jar!/:5.3.23]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.23.jar!/:5.3.23]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.65.jar!/:na]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.65.jar!/:na]
at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.3.23.jar!/:5.3.23]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.23.jar!/:5.3.23]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.65.jar!/:na]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.65.jar!/:na]
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) [tomcat-embed-core-9.0.65.jar!/:na]
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat-embed-core-9.0.65.jar!/:na]
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [tomcat-embed-core-9.0.65.jar!/:na]
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [tomcat-embed-core-9.0.65.jar!/:na]
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.65.jar!/:na]
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat-embed-core-9.0.65.jar!/:na]
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) [tomcat-embed-core-9.0.65.jar!/:na]
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) [tomcat-embed-core-9.0.65.jar!/:na]
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.65.jar!/:na]
at org.apache.coyote.AbstractProtocolConnectionHandler.process(AbstractProtocol.java:890)[tomcat−embed−core−9.0.65.jar!/:na]atorg.apache.tomcat.util.net.NioEndpointSocketProcessor.doRun(NioEndpoint.java:1789) [tomcat-embed-core-9.0.65.jar!/:na]
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.65.jar!/:na]
at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-embed-core-9.0.65.jar!/:na]
at org.apache.tomcat.util.threads.ThreadPoolExecutorWorker.run(ThreadPoolExecutor.java:659)[tomcat−embed−core−9.0.65.jar!/:na]atorg.apache.tomcat.util.threads.TaskThreadWrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.65.jar!/:na]
at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
Caused by: java.lang.IllegalArgumentException: java.security.InvalidKeyException: Illegal key size
at com.github.binarywang.wxpay.v3.util.AesUtils.decryptToString(AesUtils.java:74) ~[weixin-java-pay-4.4.0.jar!/:na]
at com.github.binarywang.wxpay.v3.auth.AutoUpdateCertificatesVerifier.deserializeToCerts(AutoUpdateCertificatesVerifier.java:200) ~[weixin-java-pay-4.4.0.jar!/:na]
at com.github.binarywang.wxpay.v3.auth.AutoUpdateCertificatesVerifier.autoUpdateCert(AutoUpdateCertificatesVerifier.java:166) ~[weixin-java-pay-4.4.0.jar!/:na]
at com.github.binarywang.wxpay.v3.auth.AutoUpdateCertificatesVerifier.(AutoUpdateCertificatesVerifier.java:109) ~[weixin-java-pay-4.4.0.jar!/:na]
at com.github.binarywang.wxpay.config.WxPayConfig.initApiV3HttpClient(WxPayConfig.java:285) ~[weixin-java-pay-4.4.0.jar!/:na]
... 56 common frames omitted
Caused by: java.security.InvalidKeyException: Illegal key size
at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039) ~[na:1.8.0_121]
at javax.crypto.Cipher.implInit(Cipher.java:805) ~[na:1.8.0_121]
at javax.crypto.Cipher.chooseProvider(Cipher.java:864) ~[na:1.8.0_121]
at javax.crypto.Cipher.init(Cipher.java:1396) ~[na:1.8.0_121]
at javax.crypto.Cipher.init(Cipher.java:1327) ~[na:1.8.0_121]
at com.github.binarywang.wxpay.v3.util.AesUtils.decryptToString(AesUtils.java:67) ~[weixin-java-pay-4.4.0.jar!/:na]
... 60 common frames omitted

```

**Comment by binarywang** [comment]
> Caused by: java.security.InvalidKeyException: Illegal key size
这是错误的根源吧？看下wiki常见问题吧

**Comment by coder8088** [comment]
感谢大佬，已经解决了，不好意思提了个无效问题，后面仔细看看文档 :)

**Comment by fhqmwy** [comment]
> 感谢大佬，已经解决了，不好意思提了个无效问题，后面仔细看看文档 :)

怎么解决的
