### ISSUE TITLE
会话存档获取素材

### ISSUE THREAD

**Issue by jinxiaoyi** [Wechat-Group/WxJava#2884]
调用企业微信出现问题
me.chanjar.weixin.common.error.WxErrorException: 错误代码：-99, 错误信息：getmediadata err ret 10002
 at me.chanjar.weixin.cp.api.impl.WxCpMsgAuditServiceImpl.getMediaFile(WxCpMsgAuditServiceImpl.java:176)

* WxJava 模块名:  weixin-cp
* WxJava 版本号:  4.4.0

### 详细描述
会话存档从4.3.5.B升级到4.4.0后会出现这个问题.  拉取媒体文件会出现.    出现频率较高.   sdk我使用getChatDatas()获取的sdk透传给
getMediaFile()然后
me.chanjar.weixin.common.error.WxErrorException: 错误代码：-99, 错误信息：getmediadata err ret 10002
 at me.chanjar.weixin.cp.api.impl.WxCpMsgAuditServiceImpl.getMediaFile(WxCpMsgAuditServiceImpl.java:176)
 at com.blackhole.app.sys.service.thirdparty.DialogueServiceImpl.getMediaData(DialogueServiceImpl.java:85)
 at com.blackhole.app.sys.service.thirdparty.WxCorpServiceImpl.getMediaData(WxCorpServiceImpl.java:1125)
 at com.blackhole.app.sys.service.es.impl.ChatMsgRecordEsServiceImpl.buildMsgRecord(ChatMsgRecordEsServiceImpl.java:483)
 at com.blackhole.app.sys.service.es.impl.ChatMsgRecordEsServiceImpl.dealDialogue(ChatMsgRecordEsServiceImpl.java:164)
 at com.blackhole.app.sys.job.DialogueSyncHandler.execute(DialogueSyncHandler.java:65)
 at sun.reflect.GeneratedMethodAccessor2981.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at com.xxl.job.core.handler.impl.MethodJobHandler.execute(MethodJobHandler.java:31)
 at com.xxl.job.core.thread.JobThread.run(JobThread.java:163)

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f625e88e532, pid=1, tid=0x00007f5fc91d5700
#
# JRE version: OpenJDK Runtime Environment (8.0_111-b14) (build 1.8.0_111-8u111-b14-2~bpo8+1-b14)
# Java VM: OpenJDK 64-Bit Server VM (25.111-b14 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libc.so.6+0x36532]  abort+0x232
#
# Core dump written. Default location: //core or core.1
#
# An error report file with more information is saved as:
# //hs_err_pid1.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.

最后服务节点挂了
[error occurred during error reporting , id 0xb]

[error occurred during error reporting , id 0xb]

[error occurred during error reporting , id 0xb]

[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]
[Too many errors, abort]

**Comment by jinxiaoyi** [comment]
不是百分百出现. 能正常拉取文本和部分图片.  出现这个问题. 我们的java服务节点就会挂掉

**Comment by 0katekate0** [comment]
10002 | 数据解析失败 | 建议重试请求。若仍失败，可以反馈给企业微信进行查询，请提供sdk接口参数与调用时间点等信息

在代码里面捕获异常，对业务进行单独处理

**Comment by jinxiaoyi** [comment]
> 10002 | 数据解析失败 | 建议重试请求。若仍失败，可以反馈给企业微信进行查询，请提供sdk接口参数与调用时间点等信息
> 
> 在代码里面捕获异常，对业务进行单独处理

我们已经捕获异常了 . 就算这条数据不保存也没问题. 但是我们java服务好像溢出下线了.    现在就是想知道为啥溢出下线了

**Comment by jinxiaoyi** [comment]
> > 10002 | 数据解析失败 | 建议重试请求。若仍失败，可以反馈给企业微信进行查询，请提供sdk接口参数与调用时间点等信息
> > 在代码里面捕获异常，对业务进行单独处理
> 
> 我们已经捕获异常了 . 就算这条数据不保存也没问题. 但是我们java服务好像溢出下线了. 现在就是想知道为啥溢出下线了

下面这个是sdk的报错日志. 不知道你能不能看懂
https://share.weiyun.com/aNtdtDCr

**Comment by 0katekate0** [comment]
你要看是什么原因导致的内存溢出，堆栈文件里面描述了，Java_com_tencent_wework_Finance_GetMediaData，代表是企微libWeWorkFinanceSdk_Java.so里面的GetMediaData方法调用报错10002 | 数据解析失败，重试下，如果还不行，官方文档上说反馈给企微进行查询

**Comment by jinxiaoyi** [comment]
> 你要看是什么原因导致的内存溢出，堆栈文件里面描述了，Java_com_tencent_wework_Finance_GetMediaData，代表是企微libWeWorkFinanceSdk_Java.so里面的GetMediaData方法调用报错10002 | 数据解析失败，重试下，如果还不行，官方文档上说反馈给企微进行查询

https://developer.work.weixin.qq.com/community/question/detail?content_id=16392797595394921726
这是我在企微社区的帖子.   之前10010也会溢出.  就很奇怪
