### ISSUE TITLE
微信支付Web支付返回字符串非JSON

### ISSUE THREAD

**Issue by chj9** [Wechat-Group/WxJava#2900]
### 简要描述
微信支付web支付返回字符串而非JSON，同个版本，我们在开发环境测试的时候就是返回了JSON，测试正常，上线运行一段时间后报异常

### 模块版本情况
* WxJava 模块名:  weixin-java-pay
* WxJava 版本号: 4.4.0

### 详细描述
有问题代码
```
    @ChannelMsgLog(tag = "web")
    public WechatOrderPayResponse webPay(WxPayUnifiedOrderV3Request request) throws Exception {
        WxPayService wxPayService = weChatPayContextClient.getPayServiceByMchId(request.getMchid());
        WxPayUnifiedOrderV3Result createOrderResult = wxPayService.createOrderV3(TradeTypeEnum.NATIVE, request);
        WechatOrderPayResponse result = new WechatOrderPayResponse();
        result.setCodeUrl(createOrderResult.getCodeUrl());
        return result;
    }
```
WxPayUnifiedOrderV3Result createOrderResult = wxPayService.createOrderV3(TradeTypeEnum.NATIVE, request);
这行报错，实际返回返回如下，同个版本以前返回的是JSON串的，所以才会测试通过上线了。
![image](https://user-images.githubusercontent.com/16426260/207242933-2916920a-1783-4553-ad4c-09544488f86b.png)

SDK内部打印
![image](https://user-images.githubusercontent.com/16426260/207245149-0f347320-e314-451d-a6df-54d74afaa438.png)

### 日志
异常如下
```
java.lang.ClassCastException: class java.lang.String cannot be cast to class com.github.binarywang.wxpay.bean.result.WxPayUnifiedOrderV3Result (java.lang.String is in module java.base of loader 'bootstrap'; com.github.binarywang.wxpay.bean.result.WxPayUnifiedOrderV3Result is in unnamed module of loader 'app')
com.qibingdaojia.turnright.pay.client.WeChatPayClient.webPay(WeChatPayClient.java:46)
	at com.qibingdaojia.turnright.pay.client.WeChatPayClient$$FastClassBySpringCGLIB$$d9b461b8.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:102)

```

**Comment by binarywang** [comment]
那这个问题该怎么解决？有时候返回json，有时候返回字符串？

**Comment by chj9** [comment]
> 那这个问题该怎么解决？有时候返回json，有时候返回字符串？

目前解决方式
![企业微信截图_16712624183465](https://user-images.githubusercontent.com/16426260/208231155-b5e212f7-3f8e-4ab0-96b5-a9844d7ad734.png)

String强转。只是担心以后又会出现返回json串的情况。
