### ISSUE TITLE
Illegal base64 character 3f

### ISSUE THREAD

**Issue by goubuy** [Wechat-Group/WxJava#2951]
Caused by: java.lang.IllegalArgumentException: Illegal base64 character 3f
at java.util.Base64$Decoder.decode0(Base64.java:714)
at java.util.Base64$Decoder.decode(Base64.java:526)
at java.util.Base64$Decoder.decode(Base64.java:549)
at com.github.binarywang.wxpay.v3.util.PemUtils.loadPrivateKey(PemUtils.java:38)
at com.github.binarywang.wxpay.config.WxPayConfig.initApiV3HttpClient(WxPayConfig.java:275)

**Comment by binarywang** [comment]
非法字符？

建议看下是否指定的是正确的文件

**Comment by glowxq** [comment]
我也遇到了这个问题

**Comment by glowxq** [comment]
Caused by: java.lang.IllegalArgumentException: Illegal base64 character 3a
	at java.base/java.util.Base64$Decoder.decode0(Base64.java:852)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:570)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:593)
	at com.github.binarywang.wxpay.config.WxPayConfig.loadConfigInputStream(WxPayConfig.java:395)
	at com.github.binarywang.wxpay.config.WxPayConfig.initApiV3HttpClient(WxPayConfig.java:299)
	... 64 common frames omitted

**Comment by binarywang** [comment]
看看文本内容是否有问题，是否可能被篡改？

**Comment by glowxq** [comment]
可能是我配置问题，启动时候 报错 无法找到对应mchId=【xxxx】,appId=【xxxxx】的商户号配置信息，请核实！

**Comment by glowxq** [comment]
configContent = Base64.getDecoder().decode(configString);  configString = classpath:cert/apiclient_key.pem Base64 解码器的工作逻辑：Base64.getDecoder().decode(String) 要求输入一个 纯Base64编码的字符串，但你的输入是 "classpath:cert/apiclient_key.pem"，这是一个文件路径字符串，其中包含非法Base64字符 :（十六进制 0x3a），导致解码失败。
PEM文件的本质：PEM格式文件（如 apiclient_key.pem）通常包含 Base64编码的密钥数据，但文件内容会包含额外的页眉/页脚标记（如 -----BEGIN PRIVATE KEY-----）和换行符。直接解码整个文件内容会失败，必须提取纯Base64部分。
