### ISSUE TITLE
NoSuchFieldError Companion OkHttpSimplePostRequestExecutor

### ISSUE THREAD

**Issue by fire97** [Wechat-Group/WxJava#2987]
问题：
在使用okhttp的post请求调用微信接口的时候出现报错 NoSuchFieldError，
经排查，应该是okhttp版本的问题，导致OkHttpSimplePostRequestExecutor中RequestBody.Companion.create(postEntity, MediaType.parse("text/plain; charset=utf-8"));
找不到需要的静态类Companion，
猜测修改版本可以解决问题，但是不确定正确的版本要求是多少，，能否提供一下对应的版本或者其他解决方案

咨询：

还有就是SimplePostRequestExecutor.create(RequestHttp requestHttp)方法中直接根据请求类型使用指定的Executor进行处理，这块地方有没有可能修改为可扩展的方式呢，允许外部修改Executor

日志：
Caused by: java.lang.NoSuchFieldError: Companion
	at me.chanjar.weixin.common.util.http.okhttp.OkHttpSimplePostRequestExecutor.execute(OkHttpSimplePostRequestExecutor.java:27) ~[weixin-java-common-4.3.0.jar:?]
	at me.chanjar.weixin.common.util.http.okhttp.OkHttpSimplePostRequestExecutor.execute(OkHttpSimplePostRequestExecutor.java:19) ~[weixin-java-common-4.3.0.jar:?]
	at cn.binarywang.wx.miniapp.api.impl.BaseWxMaServiceImpl.executeInternal(BaseWxMaServiceImpl.java:270) ~[weixin-java-miniapp-4.3.0.jar:?]
	at cn.binarywang.wx.miniapp.api.impl.BaseWxMaServiceImpl.execute(BaseWxMaServiceImpl.java:224) ~[weixin-java-miniapp-4.3.0.jar:?]
	at cn.binarywang.wx.miniapp.api.impl.BaseWxMaServiceImpl.post(BaseWxMaServiceImpl.java:198) ~[weixin-java-miniapp-4.3.0.jar:?]
	at cn.binarywang.wx.miniapp.api.impl.WxMaUserServiceImpl.getNewPhoneNoInfo(WxMaUserServiceImpl.java:68) ~[weixin-java-miniapp-4.3.0.jar:?]

**Comment by binarywang** [comment]
你参考本项目的pom依赖就知道应该用哪个版本了

**Comment by binarywang** [comment]
另外不同的问题请单独提出，谢谢
