### ISSUE TITLE
服务商批量转账下载电子回单正常、异常情况都处理报错

### ISSUE THREAD

**Issue by wincham** [Wechat-Group/WxJava#3032]
### 简要描述
服务商批量转账下载电子回单报错：1.微信正确返回流，但代码报空指针异常 2.微信未正确返回文件流时，未正确处理

### 模块版本情况
* WxJava 模块名: weixin-java-pay
* WxJava 版本号: 4.5.0

### 详细描述
拿到下载地址，调用下载接口

### 日志
`微信返回错误提示，响应头未携带相关校验参数导致响应处理异常`
```
WxPayException(customErrorMsg=null, returnCode=null, returnMsg=null, resultCode=null, errCode=null, errCodeDes=null, xmlString=null)
	at com.github.binarywang.wxpay.service.impl.WxPayServiceApacheHttpImpl.downloadV3(WxPayServiceApacheHttpImpl.java:276)
	at com.github.binarywang.wxpay.service.impl.PartnerTransferServiceImpl.transferDownload(PartnerTransferServiceImpl.java:282)
	at com.dcz.pay.test.BillReceiptTest.queryBillReceiptDetailTest(BillReceiptTest.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.github.binarywang.wxpay.service.impl.WxPayServiceApacheHttpImpl.downloadV3(WxPayServiceApacheHttpImpl.java:262)
	... 24 more
Caused by: org.apache.http.HttpException: 应答的微信支付签名验证失败
	at com.github.binarywang.wxpay.v3.SignatureExec.executeWithSignature(SignatureExec.java:85)
	at com.github.binarywang.wxpay.v3.SignatureExec.execute(SignatureExec.java:61)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	... 27 more
```
`微信正确返回响应流，但是未携带Content-Type导致报空指针异常`
```
WxPayException(customErrorMsg=null, returnCode=null, returnMsg=null, resultCode=null, errCode=null, errCodeDes=null, xmlString=null)
	at com.github.binarywang.wxpay.service.impl.WxPayServiceApacheHttpImpl.downloadV3(WxPayServiceApacheHttpImpl.java:276)
	at com.github.binarywang.wxpay.service.impl.PartnerTransferServiceImpl.transferDownload(PartnerTransferServiceImpl.java:282)
	at com.dcz.pay.test.BillReceiptTest.queryBillReceiptDetailTest(BillReceiptTest.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.NullPointerException
	at com.github.binarywang.wxpay.v3.auth.WxPayValidator.validate(WxPayValidator.java:28)
	at com.github.binarywang.wxpay.v3.SignatureExec.executeWithSignature(SignatureExec.java:84)
	at com.github.binarywang.wxpay.v3.SignatureExec.execute(SignatureExec.java:61)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.github.binarywang.wxpay.service.impl.WxPayServiceApacheHttpImpl.downloadV3(WxPayServiceApacheHttpImpl.java:262)
	... 24 more
```

**Comment by binarywang** [comment]
欢迎提交PR代码进行修复，我看你代码都已经准备好了吧

**Comment by wincham** [comment]
> 欢迎提交PR代码进行修复，我看你代码都已经准备好了吧

诶，忘记提交了
