### ISSUE TITLE
由于引用了Gson，在JDK17中出现无法序列化的错误

### ISSUE THREAD

**Issue by safziy** [Wechat-Group/WxJava#3054]
### 简要描述
使用了JDK17，导致消息序列化失败

### 模块版本情况
* WxJava 模块名: mp

### 日志
```
SLF4J: Failed toString() invocation on an object of type [me.chanjar.weixin.mp.config.impl.WxMpDefaultConfigImpl]
Reported exception:
com.google.gson.JsonIOException: Failed making field 'java.io.File#path' accessible; either increase its visibility or write a custom TypeAdapter for its declaring type.
        at com.google.gson.internal.reflect.ReflectionHelper.makeAccessible(ReflectionHelper.java:38)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:286)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130)
        at com.google.gson.Gson.getAdapter(Gson.java:556)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:160)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:294)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130)
        at com.google.gson.Gson.getAdapter(Gson.java:556)
        at com.google.gson.Gson.toJson(Gson.java:834)
        at com.google.gson.Gson.toJson(Gson.java:812)
        at com.google.gson.Gson.toJson(Gson.java:759)
        at com.google.gson.Gson.toJson(Gson.java:736)
        at me.chanjar.weixin.mp.config.impl.WxMpDefaultConfigImpl.toString(WxMpDefaultConfigImpl.java:181)
        at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:291)
        at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:263)
        at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:225)
        at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:160)
        at ch.qos.logback.classic.spi.LoggingEvent.getFormattedMessage(LoggingEvent.java:397)
        at ch.qos.logback.classic.spi.LoggingEvent.prepareForDeferredProcessing(LoggingEvent.java:253)
        at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:226)
        at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:102)
        at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:85)
        at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
        at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:272)
        at ch.qos.logback.classic.Logger.callAppenders(Logger.java:259)
        at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:426)
        at ch.qos.logback.classic.Logger.filterAndLog_1(Logger.java:402)
        at ch.qos.logback.classic.Logger.info(Logger.java:588)
        at com.safziy.mp.controller.MpController.weixinMpVMessage(MpController.java:36)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:143)
        at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:82)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @1888ff2c
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
        at com.google.gson.internal.reflect.ReflectionHelper.makeAccessible(ReflectionHelper.java:35)
```

**Comment by binarywang** [comment]
你有什么改进建议？欢迎直接PR展示你的代码

**Comment by wikitx** [comment]
更换成fastjson2吧。
fastjson2 从版本2.0.15开始已经支持了JDK17

**Comment by ariwori** [comment]
这个问题今天我也遇到了版本 4.6.0

**Comment by glowxq** [comment]
作者不处理吗?

**Comment by binarywang** [comment]
> 作者不处理吗?

暂时没有好的办法，更换框架也不现实，毕竟底层依赖太多，不是很容易改的。
如果你方便，可以帮忙探索下如何修改才影响更小。

**Comment by glowxq** [comment]
这边在设置的时候是有发现能够规避一些问题,在构建配置阶段规避后目前展示没有发现其他问题.后续有时间的话我拉源码下来处理下. 不过更好的方案感觉还是升级替换掉 gson

**Comment by binarywang** [comment]
> 这边在设置的时候是有发现能够规避一些问题,在构建配置阶段规避后目前展示没有发现其他问题.后续有时间的话我拉源码下来处理下. 不过更好的方案感觉还是升级替换掉 gson

可以，感谢，期待你的代码

**Comment by duanQiaoo** [comment]
我也遇到这个问题了，接入小程序模块，各位大佬有解决的吗？

**Comment by duanQiaoo** [comment]
> 我也遇到这个问题了，接入小程序模块，各位大佬有解决的吗？

自己来回答下解决过程：
按照chatgpt提示的在spring-boot-maven-plugin下增加了
<configuration>
    <jvmArguments>--add-opens=java.base/java.io=ALL-UNNAMED</jvmArguments>
</configuration>
但是并没有起作用，无论是在父pom中加，还是子pom中加都不行
后来在命令行执行 mvn spring-boot:run 突然就好了，报错是另外一个 java.util.concurrent.locks 包找不到
遂全加上了，如下
                     <jvmArguments>
                            --add-opens=java.base/java.io=ALL-UNNAMED
                            --add-opens=java.base/java.lang=ALL-UNNAMED
                            --add-opens=java.base/java.util=ALL-UNNAMED
                            --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
                            --add-opens=java.base/java.util.concurrent.locks=ALL-UNNAMED
                            --add-opens=java.base/java.nio=ALL-UNNAMED
                            --add-opens=java.base/java.net=ALL-UNNAMED
                            --add-opens=java.base/java.security=ALL-UNNAMED
                        </jvmArguments>
又有新的报错是，appId找不到，这是因为我是一个多模块项目，在user模块的application.yml中配置的appId，在启动类中没有，于是我把配置从user中挪到了主启动类的application.yml中，服务正常启动
后来我又把上述的jvmArguments参数也删去，服务也都正常启动。
问题就发生在 我把 appId 跟 secret 配置错了地方？

先暂时记录下解决过程和方法，有空再研究下为什么是这样。

**Comment by glowxq** [comment]
好的，我暂时通过别的方法绕过去了。后续有时间都话解决下



---原始邮件---
发件人: "Binary ***@***.***&gt;
发送时间: 2024年8月21日(周三) 下午4:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Wechat-Group/WxJava] 由于引用了Gson，在JDK17中出现无法序列化的错误 (Issue #3054)




  
作者不处理吗?
  
暂时没有好的办法，更换框架也不现实，毕竟底层依赖太多，不是很容易改的。
 如果你方便，可以帮忙探索下如何修改才影响更小。

**Comment by TinChi0818** [comment]
尝试添加依赖：
```
<dependency>
    <groupId>org.burningwave</groupId>
    <artifactId>core</artifactId>
    <version>9.5.2</version>
</dependency>
```
然后在启动类里的main方法的第一行添加：
```
public static void main(String[] args) {
    StaticComponentContainer.Modules.exportAllToAll();
    Solon.start(Application.class, args);
}
```

**Comment by binarywang** [comment]
> 尝试添加依赖：
> 
> ```
> <dependency>
>     <groupId>org.burningwave</groupId>
>     <artifactId>core</artifactId>
>     <version>9.5.2</version>
> </dependency>
> ```
> 
> 然后在启动类里的main方法的第一行添加：
> 
> ```
> public static void main(String[] args) {
>     StaticComponentContainer.Modules.exportAllToAll();
>     Solon.start(Application.class, args);
> }
> ```

你这是在描述什么问题吗？

**Comment by TinChi0818** [comment]
> > 尝试添加依赖：
> > ```
> > <dependency>
> >     <groupId>org.burningwave</groupId>
> >     <artifactId>core</artifactId>
> >     <version>9.5.2</version>
> > </dependency>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后在启动类里的main方法的第一行添加：
> > ```
> > public static void main(String[] args) {
> >     StaticComponentContainer.Modules.exportAllToAll();
> >     Solon.start(Application.class, args);
> > }
> > ```
> 
> 你这是在描述什么问题吗？

遇到了类似的问题，JDK17下，初始化WxCpService时，WxCpDefaultConfigImpl抛出了类似异常。
```Method threw 'com.google.gson.JsonIOException' exception. Cannot evaluate me.chanjar.weixin.cp.config.impl.WxCpDefaultConfigImpl.toString()```，查询时，发现了几个类似的issue。提供一个可参考的解决方案。

或许，我应该使用适配solon的版本。。。
