### ISSUE TITLE
微信回调解析支付结果异常

### ISSUE THREAD

**Issue by luoxiaofeng1029** [Wechat-Group/WxJava#3095]
### 简要描述
支付成功后,微信回调接口,大概率会解析失败,然后微信不停的调回调接口有概率会成功.

### 模块版本情况
* WxJava 模块名: weixin-java-pay
* WxJava 版本号: 4.5.0

### 详细描述
```
public synchronized String parseOrderNotifyResult(@RequestBody String xmlData) throws WxPayException {
        log.info("开始解析微信支付回调结果");
        log.info(xmlData);
        AsQianFeiJiaoFei order = null;
        try {
            final WxPayOrderNotifyResult notifyResult = this.wxService.parseOrderNotifyResult(xmlData);
            log.info("解析微信支付回调结果成功");
            //先查询有没有处理过
            order = qianFeiJiaoFeiService.getOne(Wrappers.<AsQianFeiJiaoFei>lambdaQuery().eq(AsQianFeiJiaoFei::getUuid, notifyResult.getOutTradeNo()));
        } catch (Exception e) {
            log.error("解析微信支付回调结果失败", e);
            throw e;
        }
        if (order == null) {
            log.info("订单不存在");
            return WxPayNotifyResponse.fail("订单不存在");
        }
        if (Objects.equals(order.getState(), PayStateEnum.PAYED.getState())) {
            log.info("订单已支付");
            return WxPayNotifyResponse.success("成功");
        }
        log.info("开始更新本地订单状态");
        boolean update = qianFeiJiaoFeiService.updateOrderStateSuccess(order.getFdId());
        if (!update) {
            log.info("更新本地订单状态失败");
            return WxPayNotifyResponse.fail("更新本地订单状态失败");
        }
        log.info("更新本地订单状态成功");
        //通知远端微信支付成功
        try {
            qianFeiJiaoFeiService.writeOff(order);
        } catch (Exception e) {
            log.error("更新远端系统状态失败", e);
        }
        log.info("通知远端微信支付成功");
        return WxPayNotifyResponse.success("成功");
    }
```
一开始我以为是我业务代码的问题,没想到是parseOrderNotifyResult异常而导致跳出.后面一步步排查,发现parseOrderNotifyResult有概率对同样的xmlData解析报错.多次解析报错的日志我没贴,只贴了失败和成功的连续的日志,失败上面还有多次失败的~

### 日志
__如果日志不多，直接使用md代码引用格式贴在此处，否则如果太长，请将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，然后将其url地址贴在这里__
```
[15:20:39:802] [INFO] - com.fancy.application.anshun.gas.wx.pay.WxPayController.parseOrderNotifyResult(WxPayController.java:112) - 开始解析微信支付回调结果
[15:20:39:802] [INFO] - com.fancy.application.anshun.gas.wx.pay.WxPayController.parseOrderNotifyResult(WxPayController.java:113) - <xml><appid><![CDATA[wx26e5a42db5e26f46]]></appid>
<bank_type><![CDATA[OTHERS]]></bank_type>
<cash_fee><![CDATA[1]]></cash_fee>
<fee_type><![CDATA[CNY]]></fee_type>
<is_subscribe><![CDATA[N]]></is_subscribe>
<mch_id><![CDATA[1584445081]]></mch_id>
<nonce_str><![CDATA[1690269616659]]></nonce_str>
<openid><![CDATA[ox-V-wL57iZGdg3kpVlXTPijOldA]]></openid>
<out_trade_no><![CDATA[98fb2f7acb254433a32674e48b83e2f8]]></out_trade_no>
<result_code><![CDATA[SUCCESS]]></result_code>
<return_code><![CDATA[SUCCESS]]></return_code>
<sign><![CDATA[F68DA52A3CBF5E7B51857500F6C03ECA]]></sign>
<time_end><![CDATA[20230725152023]]></time_end>
<total_fee>1</total_fee>
<trade_type><![CDATA[MWEB]]></trade_type>
<transaction_id><![CDATA[4200001870202307259861214315]]></transaction_id>
</xml>
[15:20:39:805] [ERROR] - com.fancy.application.anshun.gas.wx.pay.WxPayController.parseOrderNotifyResult(WxPayController.java:121) - 解析微信支付回调结果失败
com.github.binarywang.wxpay.exception.WxPayException: 发生异常！
	at com.github.binarywang.wxpay.service.impl.BaseWxPayServiceImpl.parseOrderNotifyResult(BaseWxPayServiceImpl.java:325) ~[weixin-java-pay-4.5.0.jar:?]
	at com.github.binarywang.wxpay.service.impl.BaseWxPayServiceImpl.parseOrderNotifyResult(BaseWxPayServiceImpl.java:300) ~[weixin-java-pay-4.5.0.jar:?]
	at com.fancy.application.anshun.gas.wx.pay.WxPayController.parseOrderNotifyResult(WxPayController.java:116) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_291]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_291]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_291]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) [spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) [spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104) [spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892) [spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) [spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) [spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039) [spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) [spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) [spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908) [spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882) [spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-embed-websocket-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61) [shiro-web-1.5.3.jar:1.5.3]
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) [shiro-web-1.5.3.jar:1.5.3]
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) [shiro-web-1.5.3.jar:1.5.3]
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.5.3.jar:1.5.3]
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) [shiro-web-1.5.3.jar:1.5.3]
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449) [shiro-web-1.5.3.jar:1.5.3]
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365) [shiro-web-1.5.3.jar:1.5.3]
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90) [shiro-core-1.5.3.jar:1.5.3]
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83) [shiro-core-1.5.3.jar:1.5.3]
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387) [shiro-core-1.5.3.jar:1.5.3]
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362) [shiro-web-1.5.3.jar:1.5.3]
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.5.3.jar:1.5.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) [spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) [spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.StandardContextValve.__invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:41002) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_291]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_291]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.22.jar:9.0.22]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_291]
Caused by: java.lang.NullPointerException
	at com.github.binarywang.wxpay.bean.result.BaseWxPayResult.checkResult(BaseWxPayResult.java:352) ~[weixin-java-pay-4.5.0.jar:?]
	at com.github.binarywang.wxpay.bean.notify.WxPayOrderNotifyResult.checkResult(WxPayOrderNotifyResult.java:325) ~[weixin-java-pay-4.5.0.jar:?]
	at com.github.binarywang.wxpay.service.impl.BaseWxPayServiceImpl.parseOrderNotifyResult(BaseWxPayServiceImpl.java:320) ~[weixin-java-pay-4.5.0.jar:?]
	... 59 more
[15:20:53:797] [INFO] - com.fancy.application.anshun.gas.wx.pay.WxPayController.parseOrderNotifyResult(WxPayController.java:112) - 开始解析微信支付回调结果
[15:20:53:798] [INFO] - com.fancy.application.anshun.gas.wx.pay.WxPayController.parseOrderNotifyResult(WxPayController.java:113) - <xml><appid><![CDATA[wx26e5a42db5e26f46]]></appid>
<bank_type><![CDATA[OTHERS]]></bank_type>
<cash_fee><![CDATA[1]]></cash_fee>
<fee_type><![CDATA[CNY]]></fee_type>
<is_subscribe><![CDATA[N]]></is_subscribe>
<mch_id><![CDATA[1584445081]]></mch_id>
<nonce_str><![CDATA[1690269616659]]></nonce_str>
<openid><![CDATA[ox-V-wL57iZGdg3kpVlXTPijOldA]]></openid>
<out_trade_no><![CDATA[98fb2f7acb254433a32674e48b83e2f8]]></out_trade_no>
<result_code><![CDATA[SUCCESS]]></result_code>
<return_code><![CDATA[SUCCESS]]></return_code>
<sign><![CDATA[F68DA52A3CBF5E7B51857500F6C03ECA]]></sign>
<time_end><![CDATA[20230725152023]]></time_end>
<total_fee>1</total_fee>
<trade_type><![CDATA[MWEB]]></trade_type>
<transaction_id><![CDATA[4200001870202307259861214315]]></transaction_id>
</xml>
[15:20:53:802] [INFO] - com.fancy.application.anshun.gas.wx.pay.WxPayController.parseOrderNotifyResult(WxPayController.java:117) - 解析微信支付回调结果成功
[15:20:53:841] [INFO] - com.fancy.application.anshun.gas.wx.pay.WxPayController.parseOrderNotifyResult(WxPayController.java:132) - 开始更新本地订单状态
[15:20:53:892] [INFO] - com.fancy.application.anshun.gas.wx.pay.WxPayController.parseOrderNotifyResult(WxPayController.java:138) - 更新本地订单状态成功
[15:20:54:102] [INFO] - com.fancy.application.anshun.gas.service.impl.IQianFeiJiaoFeiServiceImpl.writeOff(IQianFeiJiaoFeiServiceImpl.java:145) - 核销成功,欠费订单ChargelGuid为:20220616151619534
[15:20:54:102] [INFO] - com.fancy.application.anshun.gas.wx.pay.WxPayController.parseOrderNotifyResult(WxPayController.java:145) - 通知远端微信支付成功
[15:26:59:721] [INFO] - com.fancy.application.anshun.gas.wx.pay.WxP
```

**Comment by luoxiaofeng1029** [comment]
@binarywang

**Comment by binarywang** [comment]
明显是报了空指针的错误，你对照源码看出是哪里的问题吗？

**Comment by luoxiaofeng1029** [comment]
> 明显是报了空指针的错误，你对照源码看出是哪里的问题吗？

问题的核心在于对同一段相同的xlmData,为什么解析大概率会失败,小概率会成功呢...微信回调发过来的数据是一样的.

**Comment by luoxiaofeng1029** [comment]
> 明显是报了空指针的错误，你对照源码看出是哪里的问题吗？

我贴出来的日志,在代码this.wxService.parseOrderNotifyResult解析的时候报的错.是相同的xmlData啊.短时间内连续报错然后又解析成功了..

**Comment by luoxiaofeng1029** [comment]
> 明显是报了空指针的错误，你对照源码看出是哪里的问题吗？

![image](https://github.com/Wechat-Group/WxJava/assets/50006313/8e0f3caf-5985-4a36-9635-4e5191322e0b)
![image](https://github.com/Wechat-Group/WxJava/assets/50006313/7dddb274-0d21-49f6-a79b-33197473246d)

目前是查到这里是空指针,我是两个商户..不知道为什么没拿到.创建订单的时候也没问题.

**Comment by luoxiaofeng1029** [comment]
> 明显是报了空指针的错误，你对照源码看出是哪里的问题吗？

![image](https://github.com/Wechat-Group/WxJava/assets/50006313/faba57db-9b89-45c7-82ad-dca3efcfb634)
根据不同的mchId,this.wxService.switchover(mchId);然后创建订单没问题.

**Comment by luoxiaofeng1029** [comment]
@binarywang 很急啊...好几天了 没办法交付

**Comment by 0katekate0** [comment]
> @binarywang 很急啊...好几天了 没办法交付

刚发版，你用最新版，应该可以了

**Comment by luoxiaofeng1029** [comment]
> > @binarywang 很急啊...好几天了 没办法交付
> 
> 刚发版，你用最新版，应该可以了

我刚试了 <version>4.5.3.B</version>,还是不行,我看了你们的最新提交记录,,没有这块变更的代码啊.ε=(´ο｀*)))唉

**Comment by luoxiaofeng1029** [comment]
> > @binarywang 很急啊...好几天了 没办法交付
> 
> 刚发版，你用最新版，应该可以了

我也不能百分之百确定是你们代码有问题,但是我找不到我的问题在哪.ε=(´ο｀*)))

**Comment by cloudX2019** [comment]
![image](https://github.com/Wechat-Group/WxJava/assets/24669502/5a8fe83c-a449-48ba-a688-56cfc5e395b4)
这里解析的时候需要.switchover(mchId).parseOrderNotifyResult()。偶尔成功偶尔失败是因为微信每次回调请求时响应的线程不一样，ThreadLocal中的商户号是错误的或者没有导致获取的商户号配置错误，然后解析就失败了

**Comment by 0katekate0** [comment]
> > > @binarywang 很急啊...好几天了 没办法交付
> > 
> > 
> > 刚发版，你用最新版，应该可以了
> 
> 我也不能百分之百确定是你们代码有问题,但是我找不到我的问题在哪.ε=(´ο｀*)))

楼上正解，回调过来的商户号不同，解析数据需要额外处理

**Comment by luoxiaofeng1029** [comment]
> mchId



> ![image](https://user-images.githubusercontent.com/24669502/257476155-5a8fe83c-a449-48ba-a688-56cfc5e395b4.png) 这里解析的时候需要.switchover(mchId).parseOrderNotifyResult()。偶尔成功偶尔失败是因为微信每次回调请求时响应的线程不一样，ThreadLocal中的商户号是错误的或者没有导致获取的商户号配置错误，然后解析就失败了



> ![image](https://user-images.githubusercontent.com/24669502/257476155-5a8fe83c-a449-48ba-a688-56cfc5e395b4.png) 这里解析的时候需要.switchover(mchId).parseOrderNotifyResult()。偶尔成功偶尔失败是因为微信每次回调请求时响应的线程不一样，ThreadLocal中的商户号是错误的或者没有导致获取的商户号配置错误，然后解析就失败了

你说的有道理,我当时断点到那里也是大概觉得那里有问题,但是问题是.switchover(mchId).parseOrderNotifyResult(),首先需要知道当前应该是哪个mchId;而微信返回的数据里也包含了<mch_id><![CDATA[1584445081]]></mch_id>;我觉得应该是parseOrderNotifyResult自己去识别切换呀,我怎么先拿到mchId呢,我应该是从这个解析结果的对象里拿到的mchId呀,我也可以自己解析xml;但是感觉不对劲;我现在临时办法就是先自己读出来的o(╯□╰)o

**Comment by luoxiaofeng1029** [comment]
> > > > @binarywang 很急啊...好几天了 没办法交付
> > > 
> > > 
> > > 刚发版，你用最新版，应该可以了
> > 
> > 
> > 我也不能百分之百确定是你们代码有问题,但是我找不到我的问题在哪.ε=(´ο｀*)))
> 
> 楼上正解，回调过来的商户号不同，解析数据需要额外处理

麻烦看看我下面的说法.

**Comment by 0katekate0** [comment]
> > > > > @binarywang 很急啊...好几天了 没办法交付
> > > > 
> > > > 
> > > > 刚发版，你用最新版，应该可以了
> > > 
> > > 
> > > 我也不能百分之百确定是你们代码有问题,但是我找不到我的问题在哪.ε=(´ο｀*)))
> > 
> > 
> > 楼上正解，回调过来的商户号不同，解析数据需要额外处理
> 
> 麻烦看看我下面的说法.

把你的notifyResult打印出来，帖上来看看？

**Comment by 0katekate0** [comment]
> > > > > @binarywang 很急啊...好几天了 没办法交付
> > > > 
> > > > 
> > > > 刚发版，你用最新版，应该可以了
> > > 
> > > 
> > > 我也不能百分之百确定是你们代码有问题,但是我找不到我的问题在哪.ε=(´ο｀*)))
> > 
> > 
> > 楼上正解，回调过来的商户号不同，解析数据需要额外处理
> 
> 麻烦看看我下面的说法.

你仔细断点跟下代码，就能解决了，代码是没有问题的

**Comment by 0katekate0** [comment]
> > > > > @binarywang 很急啊...好几天了 没办法交付
> > > > 
> > > > 
> > > > 刚发版，你用最新版，应该可以了
> > > 
> > > 
> > > 我也不能百分之百确定是你们代码有问题,但是我找不到我的问题在哪.ε=(´ο｀*)))
> > 
> > 
> > 楼上正解，回调过来的商户号不同，解析数据需要额外处理
> 
> 麻烦看看我下面的说法.

多商户的情况下，商户信息应该在回调接口路径上体现出来，商户号从路径参数上获取，从而就能switchover()。问题就解决了

**Comment by luoxiaofeng1029** [comment]
> 

按照你的说法,我应该先自己解析xmlData,拿到mchId,这也是我之前临时的办法,但是这也不对,我无法防止伪造的回调,我目前的理解是回调传过来的数据第一步就应该直接parseOrderNotifyResult,它里面有校验的方法可以防止伪造,xmlData里我本身也有mchId,parseOrderNotifyResult应该自己根据mchId来switchover,我在看它里面的代码,确实也有switchover,不过是在如下情况才会切换:
`  public WxPayOrderNotifyResult parseOrderNotifyResult(String xmlData, String signType) throws WxPayException {
    try {
      log.debug("微信支付异步通知请求参数：{}", xmlData);
      WxPayOrderNotifyResult result = WxPayOrderNotifyResult.fromXML(xmlData);
      if (signType == null) {
        if (result.getSignType() != null) {
          // 如果解析的通知对象中signType有值，则使用它进行验签
          signType = result.getSignType();
        } else if (configMap.get(result.getMchId()).getSignType() != null) {
          // 如果配置中signType有值，则使用它进行验签
          signType = configMap.get(result.getMchId()).getSignType();
          this.switchover(result.getMchId());
        }
      }

      log.debug("微信支付异步通知请求解析后的对象：{}", result);
      result.checkResult(this, signType, false);
      return result;
    } catch (WxPayException e) {
      throw e;
    } catch (Exception e) {
      throw new WxPayException("发生异常！", e);
    }
  }`
  只有当回调参数里没有signType,并且configMap里配置的商户的参数里有signType,才会执行 this.switchover(result.getMchId());其它则没有switchover;
归根结底,我觉得切换商户不应该由我先去解析xmlData,拿mchID自己切换;也可能是我理解不到位;

**Comment by luoxiaofeng1029** [comment]
> > > > > > @binarywang 很急啊...好几天了 没办法交付
> > > > > 
> > > > > 
> > > > > 刚发版，你用最新版，应该可以了
> > > > 
> > > > 
> > > > 我也不能百分之百确定是你们代码有问题,但是我找不到我的问题在哪.ε=(´ο｀*)))
> > > 
> > > 
> > > 楼上正解，回调过来的商户号不同，解析数据需要额外处理
> > 
> > 
> > 麻烦看看我下面的说法.
> 
> 多商户的情况下，商户信息应该在回调接口路径上体现出来，商户号从路径参数上获取，从而就能switchover()。问题就解决了

按照你的说法,我应该先自己解析xmlData,拿到mchId,这也是我之前临时的办法,但是这也不对,我无法防止伪造的回调,我目前的理解是回调传过来的数据第一步就应该直接parseOrderNotifyResult,它里面有校验的方法可以防止伪造,xmlData里我本身也有mchId,parseOrderNotifyResult应该自己根据mchId来switchover,我在看它里面的代码,确实也有switchover,不过是在如下情况才会切换:
```  
public WxPayOrderNotifyResult parseOrderNotifyResult(String xmlData, String signType) throws WxPayException {
    try {
      log.debug("微信支付异步通知请求参数：{}", xmlData);
      WxPayOrderNotifyResult result = WxPayOrderNotifyResult.fromXML(xmlData);
      if (signType == null) {
        if (result.getSignType() != null) {
          // 如果解析的通知对象中signType有值，则使用它进行验签
          signType = result.getSignType();
        } else if (configMap.get(result.getMchId()).getSignType() != null) {
          // 如果配置中signType有值，则使用它进行验签
          signType = configMap.get(result.getMchId()).getSignType();
          this.switchover(result.getMchId());
        }
      }

      log.debug("微信支付异步通知请求解析后的对象：{}", result);
      result.checkResult(this, signType, false);
      return result;
    } catch (WxPayException e) {
      throw e;
    } catch (Exception e) {
      throw new WxPayException("发生异常！", e);
    }
  }
```
只有当回调参数里没有signType,并且configMap里配置的商户的参数里有signType,才会执行 this.switchover(result.getMchId());其它则没有switchover;
归根结底,我觉得切换商户不应该由我先去解析xmlData,拿mchID自己切换;也可能是我理解不到位;

**Comment by 0katekate0** [comment]
> 

首先configMap是从ThreadLocal里面进行获取的，ThreadLocal是和线程绑定（微信用的线程池，回调回来，ThreadLocal不一定有对应的商户号）。你仔细看这个设计：
https://github.com/binarywang/weixin-java-cp-demo/blob/master/src/main/java/com/github/binarywang/demo/wx/cp/controller/mutil/WxPortalController.java

用PathVariable

**Comment by shuiyihan12** [comment]
我觉得@0katekate0 说的对,你多个商户的通知路径应该是分开的,在配置通知路径的时候带上mchId,这样微信回调你的时候你就知道mchid了.如果按你说的sdk自行切换的话,像我这种并不使用mchid作为configMap中的key,而是使用我们自定义的商户id来区分并调用支付和解析的话,sdk如果自行切换,那我的解析业务逻辑就崩了.只需要设计一个合理的回调通知url就可以解决这个问题,何乐不为

**Comment by shuiyihan12** [comment]
> 只有当回调参数里没有signType,并且configMap里配置的商户的参数里有signType,才会执行 this.switchover(result.getMchId());其它则没有switchover; 归根结底,我觉得切换商户不应该由我先去解析xmlData,拿mchID自己切换;也可能是我理解不到位;

我觉得@0katekate0 说的对,你多个商户的通知路径应该是分开的,在配置通知路径的时候带上mchId,这样微信回调你的时候你就知道mchid了.如果按你说的sdk自行切换的话,像我这种并不使用mchid作为configMap中的key,而是使用我们自定义的商户id来区分并调用支付和解析的话,sdk如果自行切换,那我的解析业务逻辑就崩了.只需要设计一个合理的回调通知url就可以解决这个问题,何乐不为
