### ISSUE TITLE
WxOpenMessageRouter解析公众号回调报错

### ISSUE THREAD

**Issue by fishwithwater** [Wechat-Group/WxJava#3121]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~

### 简要描述
从4.4.0升级到4.5.5.B后，第三方平台使用WxOpenMessageRouter解析公众号回调消息报错"无法找到对应【xxx】的公众号配置信息，请核实！"

### 模块版本情况
* WxJava 模块名: weixin-java-open
* WxJava 版本号: 4.5.5.B

### 详细描述
看sdk里面问题应该是WxOpenMessageRouter在route的时候给WxMpMessageRouter的route传了WxOpenMpService，但是WxMpMessageRouter的route里面还是会去mpService.switchoverTo(appId)，而WxOpenMpService里面configStorageMap是空的

### 日志
```
java.util.concurrent.ExecutionException: me.chanjar.weixin.common.error.WxRuntimeException: 无法找到对应【xxx】的公众号配置信息，请核实！ 
at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122) 
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191) 
at me.chanjar.weixin.mp.api.WxMpMessageRouter.lambda$route$1(WxMpMessageRouter.java:282) 
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) 
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) 
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) 
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) 
at java.base/java.lang.Thread.run(Thread.java:829) Caused by: me.chanjar.weixin.common.error.WxRuntimeException: 无法找到对应【xxx】的公众号配置信息，请核实！ 
at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.switchoverTo(BaseWxMpServiceImpl.java:599) 
at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.switchoverTo(BaseWxMpServiceImpl.java:583) 
at me.chanjar.weixin.mp.api.WxMpMessageRouter.lambda$route$0(WxMpMessageRouter.java:261) 
... 5 common frames omitted
```

**Comment by binarywang** [comment]
如果确认问题在哪里，欢迎直接提交修复PR代码，谢谢

**Comment by pengluday** [comment]
/Users/apple/develop/repos/m2Repo/com/github/binarywang/weixin-java-mp/4.5.0/weixin-java-mp-4.5.0-sources.jar!/me/chanjar/weixin/mp/api/WxMpMessageRouter.java
L212
![image](https://github.com/Wechat-Group/WxJava/assets/41465413/d5482b4c-1a64-4fff-8765-59dbf6581d74)
![image](https://github.com/Wechat-Group/WxJava/assets/41465413/f4a7cd9e-152c-4ed9-8b2d-cc30839fc472)
导致获取的appId是“default”

**Comment by wanglidong166** [comment]
此问题怎么解决呀

**Comment by pengluday** [comment]
您的邮件已收到。
