### ISSUE TITLE
退款报错 签名错误

### ISSUE THREAD

**Issue by blankhang** [Wechat-Group/WxJava#3137]
### 简要描述
调用退款接口报错签名错误

### 模块版本情况
* WxJava 模块名: wx-java-pay-spring-boot-starter
* WxJava 版本号: 4.5.5.B

### 详细描述
首先调用付款请求，成功收到回调，业务发现重复付款，调用退款报错

```yml
# 配置 wx-java-mp/pay-spring-boot-starter
wx:
  pay:
    appId: ${x.maAppId}
    apiV3Key: ${x.apiV3Key}
    mchId: ${x.mchId}
    certSerialNo:  ${x.certSerialNo}
    keyPath: classpath:wechat/apiclient_cert.p12 #apiclient_cert.p12证书文件的绝对路径或者以classpath:开头的类路径
    privateKeyPath: classpath:wechat/apiclient_key.pem #apiclient_key.pem证书文件的绝对路径或者以classpath:开头的类路径
    privateCertPath: classpath:wechat/apiclient_cert.pem #apiclient_cert.pem证书文件的绝对路径或者以classpath:开头的类路径
```
```java
        WxPayRefundRequest refundRequest = WxPayRefundRequest.newBuilder()
            // 商户订单号
            .outTradeNo(order.getTradeNo())
            // 商户退款单号
            .outRefundNo(order.getTradeNo() + "TK" + DateUtil.format(new Date(), DatePattern.PURE_DATETIME_MS_PATTERN))
            // 订单总金额 单位为分
            .totalFee(order.getAmount().multiply(new BigDecimal("100")).intValue())
            // 退款金额 单位为分
            .refundFee(order.getAmount().multiply(new BigDecimal("100")).intValue())
            // 退款原因
            .refundDesc("当前已支付，无须重复付款")
            // 退款结果通知url
            .notifyUrl(XConfig.getRefundNotifyUrl())
            .build();

        // 请求退款
        WxPayRefundResult refund = wxPayService.refund(refundRequest);
```
### 日志

```
api-xhc-admin-1  | 【请求地址】：https://api.mch.weixin.qq.com/secapi/pay/refund
api-xhc-admin-1  | 【请求数据】：<xml>
api-xhc-admin-1  |   <appid>脱敏</appid>
api-xhc-admin-1  |   <mch_id>脱敏</mch_id>
api-xhc-admin-1  |   <nonce_str>1695194131368</nonce_str>
api-xhc-admin-1  |   <sign>0A8909CFCD383041D207BAD27D5B4364</sign>
api-xhc-admin-1  |   <out_trade_no>脱敏</out_trade_no>
api-xhc-admin-1  |   <out_refund_no>脱敏</out_refund_no>
api-xhc-admin-1  |   <total_fee>1</total_fee>
api-xhc-admin-1  |   <refund_fee>1</refund_fee>
api-xhc-admin-1  |   <op_user_id>脱敏</op_user_id>
api-xhc-admin-1  |   <refund_desc>脱敏</refund_desc>
api-xhc-admin-1  | </xml>
api-xhc-admin-1  | 【响应数据】：<xml><return_code><![CDATA[FAIL]]></return_code>
api-xhc-admin-1  | <return_msg><![CDATA[签名错误]]></return_msg>
api-xhc-admin-1  | </xml>
api-xhc-admin-1  | 2023-09-20 15:15:32.349 ERROR 1 --- [o-50001-exec-17] c.g.b.w.bean.result.WxPayRefundResult    : 
api-xhc-admin-1  | 结果业务代码异常，返回结果：{return_msg=签名错误, return_code=FAIL},
api-xhc-admin-1  | 返回代码：FAIL，返回信息：签名错误
api-xhc-admin-1  | 2023-09-20 15:15:32.372 ERROR 1 --- [o-50001-exec-17] c.x.f.w.e.GlobalExceptionHandler         : 请求地址'XX/xxnotify/xxorder',发生未知异常.
api-xhc-admin-1  | 
api-xhc-admin-1  | java.lang.reflect.UndeclaredThrowableException: null
api-xhc-admin-1  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:780) ~[spring-aop-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at com.xhc.wechat.service.impl.WxOrderServiceImpl$$EnhancerBySpringCGLIB$$7a721bc9.orderPaySuccessful(<generated>) ~[xhc-wechat-1.0.0.jar!/:na]
api-xhc-admin-1  | 	at com.xhc.wechat.controller.api.WeChatPayCallbackController.parseOrderNotifyResult(WeChatPayCallbackController.java:47) ~[xhc-wechat-1.0.0.jar!/:na]
api-xhc-admin-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
api-xhc-admin-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
api-xhc-admin-1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
api-xhc-admin-1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
api-xhc-admin-1  | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072) ~[spring-webmvc-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965) ~[spring-webmvc-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:555) ~[tomcat-embed-core-9.0.79.jar!/:4.0.1]
api-xhc-admin-1  | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623) ~[tomcat-embed-core-9.0.79.jar!/:4.0.1]
api-xhc-admin-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.springframework.web.filter.AbstractRequestLoggingFilter.doFilterInternal(AbstractRequestLoggingFilter.java:289) ~[spring-web-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:111) ~[spring-web-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:111) ~[spring-web-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:114) ~[druid-1.2.16.jar!/:na]
api-xhc-admin-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at com.xhc.common.filter.RepeatableFilter.doFilter(RepeatableFilter.java:27) ~[xhc-common-1.0.0.jar!/:na]
api-xhc-admin-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:337) ~[spring-security-web-5.7.10.jar!/:5.7.10]
api-xhc-admin-1  | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115) ~[spring-security-web-5.7.10.jar!/:5.7.10]
api-xhc-admin-1  | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81) ~[spring-security-web-5.7.10.jar!/:5.7.10]
api-xhc-admin-1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.10.jar!/:5.7.10]
api-xhc-admin-1  | 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:122) ~[spring-security-web-5.7.10.jar!/:5.7.10]
api-xhc-admin-1  | 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:116) ~[spring-security-web-5.7.10.jar!/:5.7.10]
api-xhc-admin-1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.10.jar!/:5.7.10]
api-xhc-admin-1  | 	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126) ~[spring-security-web-5.7.10.jar!/:5.7.10]
api-xhc-admin-1  | 	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81) ~[spring-security-web-5.7.10.jar!/:5.7.10]
api-xhc-admin-1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.10.jar!/:5.7.10]
api-xhc-admin-1  | 	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:109) ~[spring-security-web-5.7.10.jar!/:5.7.10]
api-xhc-admin-1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.10.jar!/:5.7.10]
api-xhc-admin-1  | 	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149) ~[spring-security-web-5.7.10.jar!/:5.7.10]
api-xhc-admin-1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.10.jar!/:5.7.10]
api-xhc-admin-1  | 	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[spring-security-web-5.7.10.jar!/:5.7.10]
api-xhc-admin-1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.10.jar!/:5.7.10]
api-xhc-admin-1  | 	at com.xhc.framework.security.filter.JwtAuthenticationTokenFilter.doFilterInternal(JwtAuthenticationTokenFilter.java:41) ~[xhc-framework-1.0.0.jar!/:na]
api-xhc-admin-1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.10.jar!/:5.7.10]
api-xhc-admin-1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:111) ~[spring-web-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.10.jar!/:5.7.10]
api-xhc-admin-1  | 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103) ~[spring-security-web-5.7.10.jar!/:5.7.10]
api-xhc-admin-1  | 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89) ~[spring-security-web-5.7.10.jar!/:5.7.10]
api-xhc-admin-1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.10.jar!/:5.7.10]
api-xhc-admin-1  | 	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91) ~[spring-web-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.10.jar!/:5.7.10]
api-xhc-admin-1  | 	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) ~[spring-security-web-5.7.10.jar!/:5.7.10]
api-xhc-admin-1  | 	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) ~[spring-security-web-5.7.10.jar!/:5.7.10]
api-xhc-admin-1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.10.jar!/:5.7.10]
api-xhc-admin-1  | 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112) ~[spring-security-web-5.7.10.jar!/:5.7.10]
api-xhc-admin-1  | 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82) ~[spring-security-web-5.7.10.jar!/:5.7.10]
api-xhc-admin-1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.10.jar!/:5.7.10]
api-xhc-admin-1  | 	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55) ~[spring-security-web-5.7.10.jar!/:5.7.10]
api-xhc-admin-1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.10.jar!/:5.7.10]
api-xhc-admin-1  | 	at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42) ~[spring-security-web-5.7.10.jar!/:5.7.10]
api-xhc-admin-1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.10.jar!/:5.7.10]
api-xhc-admin-1  | 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221) ~[spring-security-web-5.7.10.jar!/:5.7.10]
api-xhc-admin-1  | 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:186) ~[spring-security-web-5.7.10.jar!/:5.7.10]
api-xhc-admin-1  | 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354) ~[spring-web-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267) ~[spring-web-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1790) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.79.jar!/:na]
api-xhc-admin-1  | 	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
api-xhc-admin-1  | Caused by: com.github.binarywang.wxpay.exception.WxPayException: 返回代码：[FAIL]，返回信息：[签名错误]，微信返回的原始报文：
api-xhc-admin-1  | <xml><return_code><![CDATA[FAIL]]></return_code>
api-xhc-admin-1  | <return_msg><![CDATA[签名错误]]></return_msg>
api-xhc-admin-1  | </xml>
api-xhc-admin-1  | 	at com.github.binarywang.wxpay.exception.WxPayException$Builder.build(WxPayException.java:207) ~[weixin-java-pay-4.5.5.B.jar!/:na]
api-xhc-admin-1  | 	at com.github.binarywang.wxpay.exception.WxPayException.from(WxPayException.java:99) ~[weixin-java-pay-4.5.5.B.jar!/:na]
api-xhc-admin-1  | 	at com.github.binarywang.wxpay.bean.result.BaseWxPayResult.checkResult(BaseWxPayResult.java:392) ~[weixin-java-pay-4.5.5.B.jar!/:na]
api-xhc-admin-1  | 	at com.github.binarywang.wxpay.service.impl.BaseWxPayServiceImpl.refund(BaseWxPayServiceImpl.java:225) ~[weixin-java-pay-4.5.5.B.jar!/:na]
api-xhc-admin-1  | 	at com.xhc.wechat.service.impl.WxOrderServiceImpl.orderPaySuccessful(WxOrderServiceImpl.java:403) ~[xhc-wechat-1.0.0.jar!/:na]
api-xhc-admin-1  | 	at com.xhc.wechat.service.impl.WxOrderServiceImpl$$FastClassBySpringCGLIB$$4a59e85d.invoke(<generated>) ~[xhc-wechat-1.0.0.jar!/:na]
api-xhc-admin-1  | 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.29.jar!/:5.3.29]
api-xhc-admin-1  | 	... 120 common frames omitted
```

**Comment by blankhang** [comment]
尝试更换过V3密钥 无效，其他接口都是OK 就退款报错

**Comment by 0katekate0** [comment]
> 尝试更换过V3密钥 无效，其他接口都是OK 就退款报错

你这是用的V3版本对吧，需要用V3版本的退款

**Comment by blankhang** [comment]
> > 尝试更换过V3密钥 无效，其他接口都是OK 就退款报错
> 
> 你这是用的V3版本对吧，需要用V3版本的退款

感谢回复，确实是改用V3就好了
