### ISSUE TITLE
临时素材下载,无法获取到文件名

### ISSUE THREAD

**Issue by jinxiaoyi** [Wechat-Group/WxJava#3146]
### 简要描述
我使用微信客服获取消息接口，客户发送了一个中文的excel。  我用框架调用下载临时素材接口报错

### 模块版本情况
* WxJava 模块名:  weixin-java-cp
* WxJava 版本号:  4.4.0

### 详细描述
获取临时素材报错
 请求地址】: https://qyapi.weixin.qq.com/cgi-bin/media/get?access_token=Bw8DlLdQfhKK-QIZl5Xk3xb79W5bGKS_m-vlqWJq5zTY6RrgBusCtB-NKsj59RQ1FzVGQtxlXWYtXc0KKPYnPXdDmvKNjfXYnOoGY7d54dySZweXNN8fLRTQ9xxGIJvQn14zB-FVu4IoJRMmKWc90xyOFNlg4U7sT2tQIpqR5hjSrC4y_fXPsv7B7O3lsAV4iY61g9UemOHdEroYQU4Thg
【请求参数】：media_id=1lbJ6IHBzaYHUyyiNoP9R1_k88ZifiWGSmKtpxdMMbz-MNy0vkMaELbcPFxUhlEPl
【错误信息】：错误代码：-99, 错误信息：无法获取到文件名，header信息有问题

我使用postman访问接口
https://qyapi.weixin.qq.com/cgi-bin/media/get?access_token=Bw8DlLdQfhKK-QIZl5Xk3xb79W5bGKS_m-vlqWJq5zTY6RrgBusCtB-NKsj59RQ1FzVGQtxlXWYtXc0KKPYnPXdDmvKNjfXYnOoGY7d54dySZweXNN8fLRTQ9xxGIJvQn14zB-FVu4IoJRMmKWc90xyOFNlg4U7sT2tQIpqR5hjSrC4y_fXPsv7B7O3lsAV4iY61g9UemOHdEroYQU4Thg&media_id=1lbJ6IHBzaYHUyyiNoP9R1_k88ZifiWGSmKtpxdMMbz-MNy0vkMaELbcPFxUhlEPl

<img width="1130" alt="image" src="https://github.com/Wechat-Group/WxJava/assets/34831856/b937ea87-60ec-47b7-8442-385a11939c38">

attachment; filename*=utf-8''GMS-%E8%81%8A%E5%A4%A9%E6%95%8F%E6%84%9F%E8%AF%8D%E5%AF%BC%E5%85%A5%E6%A8%A1%E6%9D%BF.xlsx; filename="GMS-èå¤©ææè¯å¯¼å¥æ¨¡æ¿.xlsx"

**Comment by lyfuci** [comment]
### 简要描述
和楼上一样的问题,不过问题只出现在 GIF 类型的文件同步的时候，JPG类型的文件同步是正常的

### 模块版本情况
WxJava 模块名: weixin-java-cp
WxJava 版本号: 4.5.6.B

下面是使用API调用时的报错堆栈

Caused by: me.chanjar.weixin.common.error.WxErrorException: 错误代码：-99, 错误信息：无法获取到文件名，header信息有问题
	at me.chanjar.weixin.common.util.http.HttpResponseProxy.extractFileNameFromContentString(HttpResponseProxy.java:87) ~[weixin-java-common-4.5.6.B.jar!/:na]
	at me.chanjar.weixin.common.util.http.HttpResponseProxy.getFileName(HttpResponseProxy.java:64) ~[weixin-java-common-4.5.6.B.jar!/:na]
	at me.chanjar.weixin.common.util.http.HttpResponseProxy.getFileName(HttpResponseProxy.java:43) ~[weixin-java-common-4.5.6.B.jar!/:na]
	at me.chanjar.weixin.common.util.http.apache.ApacheMediaDownloadRequestExecutor.execute(ApacheMediaDownloadRequestExecutor.java:61) ~[weixin-java-common-4.5.6.B.jar!/:na]
	at me.chanjar.weixin.common.util.http.apache.ApacheMediaDownloadRequestExecutor.execute(ApacheMediaDownloadRequestExecutor.java:30) ~[weixin-java-common-4.5.6.B.jar!/:na]
	at me.chanjar.weixin.cp.api.impl.BaseWxCpServiceImpl.executeInternal(BaseWxCpServiceImpl.java:342) ~[weixin-java-cp-4.5.6.B.jar!/:na]
	... 34 common frames omitted
