### ISSUE TITLE
使用wx-java-pay-spring-boot-starter时，不配置v3相关配置会报错

### ISSUE THREAD

**Issue by goodsnail** [Wechat-Group/WxJava#3252]
### 简要描述
按照文档 https://github.com/zsw95271/WxJava/tree/master/spring-boot-starters/wx-java-pay-spring-boot-starter 仅配置v2相关配置，会报错：请确保apiV3Key值已设置，换成wx-java-pay，手动setConfig则不会出现此问题，应该是wx-java-pay-spring-boot-starter初始化有问题。

### 模块版本情况
* wx-java-pay-spring-boot-starter: 4.6.1.B

### applicaion.yml配置：
wx:
  pay:
    appId: 
    mchId: 
    mchKey: 
    subAppId:
    subMchId:
    keyPath:

### 错误日志
Caused by: com.github.binarywang.wxpay.exception.WxPayException: 请确保apiV3Key值已设置
	at com.github.binarywang.wxpay.config.WxPayConfig.initApiV3HttpClient(WxPayConfig.java:263) ~[weixin-java-pay-4.6.0.jar:na]
	at com.github.binarywang.wxpay.config.WxPayConfig.getVerifier(WxPayConfig.java:225) ~[weixin-java-pay-4.6.0.jar:na]

**Comment by binarywang** [comment]
欢迎直接提供修复代码，谢谢

**Comment by binarypursuer** [comment]
你是启动报错吗，我看最新的代码starter是没问题的，只有调用V3的方法才会去校验APIV3Key
