### ISSUE TITLE
投诉通知验签错误

### ISSUE THREAD

**Issue by je45** [Wechat-Group/WxJava#3288]
### 简要描述
微信支付投诉通知验签错误，通知头部签名Base64解码异常。

### 模块版本情况
* WxJava 模块名: weixin-java-pay
* WxJava 版本号: 4.6.0

### 详细描述
导致的原因是因为微信的[签名探测](https://pay.weixin.qq.com/docs/merchant/development/interface-rules/signature-verification.html#%E5%BA%94%E5%AF%B9%E7%AD%BE%E5%90%8D%E6%8E%A2%E6%B5%8B%E6%B5%81%E9%87%8F)，会生成"WECHATPAY/SIGNTEST/"开头的签名值，导致签名base64解码异常。
希望能统一处理下微信签名探测流量。

### 日志
```
java.lang.IllegalArgumentException: Last unit does not have enough valid bits
	at java.util.Base64$Decoder.decode0(Base64.java:734) ~[?:1.8.0_391]
	at java.util.Base64$Decoder.decode(Base64.java:526) ~[?:1.8.0_391]
	at java.util.Base64$Decoder.decode(Base64.java:549) ~[?:1.8.0_391]
	at com.github.binarywang.wxpay.v3.auth.CertificatesVerifier.verify(CertificatesVerifier.java:33) ~[weixin-java-pay-4.6.0.jar:?]
	at com.github.binarywang.wxpay.v3.auth.CertificatesVerifier.verify(CertificatesVerifier.java:46) ~[weixin-java-pay-4.6.0.jar:?]
	at com.github.binarywang.wxpay.v3.auth.AutoUpdateCertificatesVerifier.verify(AutoUpdateCertificatesVerifier.java:121) ~[weixin-java-pay-4.6.0.jar:?]
	at com.github.binarywang.wxpay.service.impl.BaseWxPayServiceImpl.verifyNotifySign(BaseWxPayServiceImpl.java:351) ~[weixin-java-pay-4.6.0.jar:?]
	at com.github.binarywang.wxpay.service.impl.BaseWxPayServiceImpl.parseComplaintNotifyResult(BaseWxPayServiceImpl.java:1294) ~[weixin-java-pay-4.6.0.jar:?]
```

**Comment by binarywang** [comment]
你有什么修复办法，可以直接提交代码

**Comment by geqiliang** [comment]
<dependency>
    <groupId>com.github.binarywang</groupId>
    <artifactId>weixin-java-pay</artifactId>
    <version>4.6.5.B</version>
</dependency> 我已经更新pom到最新版 发现还是会报这个异常，异常后回调请求会第二次 执行来正确更新订单状态，是否是通过重新进行回调请求解决了这个异常问题
