### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: com.github.binarywang.wxpay.service.WxPayService

### ISSUE THREAD

**Issue by wenqi666** [Wechat-Group/WxJava#3332]
### 简要描述
* WxJava 模块名: 主要使用weixin-java-pay，之前已经在用weixin-java-miniapp正常的
* WxJava 版本号: 4.6.2.B 也尝试了4.6.0
* 仅进入 就报错了。
请问大佬 这种情况怎么排除异常好？

### 代码
@RequiredArgsConstructor
@Slf4j
public class WeiXinController {

  private final WxPayService wxPayService;
}

### 报错日志
 - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'weiXinController': Resolution of declared constructors on bean Class [org.dromara.booking.controller.WeiXinController] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@63947c6b] failed
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:383)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineConstructorsFromBeanPostProcessors(AbstractAutowireCapableBeanFactory.java:1294)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1189)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:962)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334)
	at org.dromara.DromaraApplication.main(DromaraApplication.java:19)
Caused by: java.lang.NoClassDefFoundError: com/github/binarywang/wxpay/service/WxPayService
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3373)
	at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2555)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:378)
	... 16 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.github.binarywang.wxpay.service.WxPayService
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 20 common frames omitted

**Comment by wenqi666** [comment]
reload maven 后得了 抱歉
