### ISSUE TITLE
v3 商家转账到零钱成功后，回调头部验证签名失败

### ISSUE THREAD

**Issue by gaoshuaitao** [Wechat-Group/WxJava#3399]
### 简要描述
商家转账到零钱成功后，商家转账批次回调通知接口中头部验证签名失败，发现微信支付证书序列号和商户的证书的序列号不一致，WxPayConfig中未找到微信支付证书序列号配置的参数，麻烦请告知

### 模块版本情况
* WxJava 模块名: weixin-java-pay
* WxJava 版本号:4.6.5.B
* 
### 日志
com.github.binarywang.wxpay.exception.WxPayException: 非法请求，头部信息验证失败
	at com.github.binarywang.wxpay.service.impl.BaseWxPayServiceImpl.baseParseOrderNotifyV3Result(BaseWxPayServiceImpl.java:368) ~[weixin-java-pay-4.6.5.B.jar:na]
	at com.github.binarywang.wxpay.service.impl.BaseWxPayServiceImpl.parseTransferBatchesNotifyV3Result(BaseWxPayServiceImpl.java:437) ~[weixin-java-pay-4.6.5.B.jar:na]
	at com.qws.oss.util.wx.pay.WxPayUtil.parseTransferBatchesNotifyV3Result(WxPayUtil.java:177) ~[classes/:na]
	at com.qws.oss.apis.controller.PayController.transferBatchesNotify(PayController.java:92) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197) ~[spring-web-5.3.9.jar:5.3.9]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141) ~[spring-web-5.3.9.jar:5.3.9]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.3.9.jar:5.3.9]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.9.jar:5.3.9]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.9.jar:5.3.9]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.9.jar:5.3.9]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1064) ~[spring-webmvc-5.3.9.jar:5.3.9]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.9.jar:5.3.9]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.9.jar:5.3.9]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.9.jar:5.3.9]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:517) ~[jakarta.servlet-api-4.0.4.jar:4.0.4]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.9.jar:5.3.9]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:584) ~[jakarta.servlet-api-4.0.4.jar:4.0.4]

**Comment by zhanyan-Ader1y** [comment]
这不是一个Issue, 如果你有疑问可以查看对应的[WIKI](https://github.com/binarywang/weixin-java-pay-demo)
