### ISSUE TITLE
微信服务号中发送模板消息时，有少部分报40003错误

### ISSUE THREAD

**Issue by poettang** [Wechat-Group/WxJava#710]
me.chanjar.weixin.common.exception.WxErrorException: {"errcode":40003,"errmsg":"invalid openid hint: [T4BDAa00124119]"}
        at me.chanjar.weixin.mp.api.impl.WxMpServiceBaseImpl.executeInternal(WxMpServiceBaseImpl.java:298)
        at me.chanjar.weixin.mp.api.impl.WxMpServiceBaseImpl.execute(WxMpServiceBaseImpl.java:239)
        at me.chanjar.weixin.mp.api.impl.WxMpServiceBaseImpl.post(WxMpServiceBaseImpl.java:228)
        at me.chanjar.weixin.mp.api.impl.WxMpTemplateMsgServiceImpl.sendTemplateMsg(WxMpTemplateMsgServiceImpl.java:35)

同样关注的一批用户，其中少部分这样，请问是有可能是哪些原因造成的。

**Comment by binarywang** [comment]
感觉不可思议，难道是微信服务器本身的问题？

**Comment by binarywang** [comment]
没有反馈，暂时关闭，如有问题直接回复即可

**Comment by beyoug** [comment]
> 没有反馈，暂时关闭，如有问题直接回复即可

确实我也遇到了这个问题

**Comment by beyoug** [comment]
@binarywang 我也是服务号，出现了这个问题，能否看一下这个问题。
`
【请求地址】: https://api.weixin.qq.com/cgi-bin/message/custom/send?access_token=xxxxxx

【请求参数】：{"touser":"xxxxxxx4f3ebb23addc13746d9b1b58","msgtype":"text","text":{"content":"你好"}}

【错误信息】：{"errcode":40003,"errmsg":"invalid openid hint: [HR0caa06863936]"}
`

**Comment by binarywang** [comment]
是不是有可能用户取消了关注？

**Comment by beyoug** [comment]
> 是不是有可能用户取消了关注？

没有取消关注，而且我发给用户送客服消息都可以成功

**Comment by binarywang** [comment]
那不清楚了，只可能是微信接口出问题，或者提示信息有问题，总之是bug，可以向微信官方反映一下。
